LICENSE
README.md

Adds a license

---

Rakefile

this provides
```
rake graphql:schema:dump
```

Add graphQL schema rake tasks

---

README.md

Adding how to approve, reject and finalize orders.

Add partner order actions to README

---

app/graphql/types/order_connection_sort_enum.rb
app/graphql/types/query_type.rb
spec/controllers/api/requests/orders_query_request_spec.rb

Addresses [CP-56](https://artsyproduct.atlassian.net/browse/CP-56). Adds option to sort orders by `updated_at` in ascending/descending order.

Add sort by updated_at option for orders

---

dangerfile.ts

Pairs with https://github.com/artsy/peril-settings/pull/70

Adds a dangerfile, which runs on Peril, to the repo

---

hokusai/production.yml

Fix production.yml

---

app/models/order.rb
spec/models/order_spec.rb

I happened to notice a bug here, so I wrote a failing test ("with a line item that has no price") and then fixed it. ❤️

Add spec and simplify price computation

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/order.rb
db/migrate/20180629185502_create_versions.rb
db/schema.rb

Following up on discussion in https://github.com/artsy/exchange/pull/49, adding Paper Trail and tracking changes in Order.

Add Paper Trail and track changes on Order

---

config/application.rb
lib/adapters/gravity_v1.rb

following up on https://github.com/artsy/exchange/pull/65
cc @alloy

Move the require to the file that actually depends on it

---

app/models/order.rb
spec/models/order_spec.rb

https://www.notion.so/artsy/Define-order-number-structure-65e2d9186f214b1184113a9d5a010b3b

Update order code to match expected format

---

Gemfile
Gemfile.lock

Fix missing gem

---

app/controllers/concerns/auth_handler.rb
app/graphql/types/query_type.rb
spec/controllers/api/requests/order_query_request_spec.rb
spec/controllers/api/requests/orders_query_request_spec.rb
spec/support/auth_helper.rb
spec/support/graphlient_client.rb

short and sweet, with @ashkan18's help

allow trusted users to perform graphql queries

---

app/controllers/api/base_api_controller.rb

I actually am not sure why this was working correctly before, but this appears to fix the exchange issues we've been seeing.

Fix csrf issue

---

README.md

Fix link to token instructions

---

Dockerfile

After seeing @izakp's comments, I thought I should update Exchange too.

switch from bitnami/ruby:2.5.1 to official ruby:2.5.1 for performance

---

Gemfile
Gemfile.lock
app/events/order_event.rb
spec/events/order_event_spec.rb

https://github.com/artsy/pulse/pull/229 depends on this.

Expose state_expires_at field for OrderEvent

---

app/models/order.rb
app/services/order_service.rb
app/services/order_submit_service.rb

With current code, our service layer code is very fragile in terms of we need to first call state change method first, then do some stuff and then save.
```ruby
order.with_lock do
order.approve!
charge = PaymentService.capture_charge(order.external_charge_id)
TransactionService.create_success!(order, charge)
order.save!
end
```
Update state change methods to get a block, and also save the change after running the block if given. With this change the code above will look like
```ruby
order.approve! do
charge = PaymentService.capture_charge(order.external_charge_id)
TransactionService.create_success!(order, charge)
end
```
Updated state changes method to get an optional block and also save the order changes afterwards.
1) Also moved the order locking logic in the state change methods, im …

Refactor state methods to get a block and also save the order

---

app/graphql/types/order_type.rb
spec/controllers/api/requests/orders_query_request_spec.rb

Followup on #122  which was followup on #119 
Basically here make sure we handle `null` for `fulfillment_type`.

Fix null fulfillment_type issue

---

app/graphql/types/order_type.rb
spec/controllers/api/requests/orders_query_request_spec.rb

Revert "Fix null fulfillment_type issue"

---

app/graphql/types/fulfillment_union_type.rb
app/graphql/types/order_type.rb
spec/controllers/api/requests/set_shipping_mutation_request_spec.rb

Revert "Some Follow up on order requested fulfillment"

---

app/graphql/types/query_type.rb
spec/controllers/api/requests/order_query_request_spec.rb

Slack discussion is [here](https://artsy.slack.com/archives/C9ZJYFDNF/p1534970696000100).

Allow sales_admin to access all orders

---

README.md
app/graphql/mutations/submit_order.rb
spec/controllers/api/requests/submit_order_mutation_request_spec.rb

I mostly cargo-culted this based on #93

Use new mutation style for submit_order

---

app/events/order_event.rb
spec/events/order_event_spec.rb

TRACKED IN: https://artsyproduct.atlassian.net/browse/PURCHASE-420

add buyer type to order event

---

app/events/order_event.rb
spec/events/order_event_spec.rb

Spotted this was missing when reading the code,

Adds the buyer id to the event going out to the event service

---

app/graphql/inputs/shipping_attributes.rb
app/graphql/mutations/set_shipping.rb
app/graphql/types/requested_fulfillment_union_type.rb
app/services/order_service.rb
spec/controllers/api/requests/set_shipping_mutation_request_spec.rb

:warning: Do not merge until we have all PRs related to this change in place and approved. 
here it is working in exchange local:

[COORDINATED MERGE] move phone_number to shipping input and Ship output

---

README.md

Added a section to describe possible steps for debugging errors on Exchange.

Update README with debugging info

---

app/admin/orders.rb
app/models/order.rb

Remove this for now, we can add it back in later if we need it

Remove last admin note attribute/filter

---

Gemfile
Gemfile.lock
config/initializers/datadog.rb
hokusai/production.yml
hokusai/staging.yml

This gets datadog tracing set up. Then once that's good I'll submit another PR for statsd/metric tracking.

add datadog tracing

---

config/initializers/datadog.rb

let me turn on debugging

---

config/initializers/datadog.rb

wrong env var name

---

README.md
config/initializers/datadog.rb

graphql tracing

---

app/admin/orders.rb
app/models/admin_note.rb

for https://artsyproduct.atlassian.net/browse/PLATFORM-844

Add admin note functionality to exchange

---

app/services/sales_tax_service.rb
config/routes.rb

Resolves https://sentry.io/artsynet/exchange-staging/issues/678478367
and
https://sentry.io/artsynet/exchange-staging/issues/711198622

fix uncaptured nil error

---

app/admin/orders.rb

Fixes 
https://artsyproduct.atlassian.net/browse/PLATFORM-971

Add support for searching by code

---

app/admin/admin_notes.rb
app/admin/orders.rb
config/routes.rb
db/migrate/20181012183706_fix_admin_note_column_name.rb
db/schema.rb

List of changes:
- Add separate new admin note page
- change some link styles to buttons
- add check for credit card info before call to gravity
- change column name to from keyword type

Db migration to have ability to add admin notes

---

app/admin/orders.rb
app/models/order.rb

Flesh out more of the exchange admin page
- Add all orders scope
- Populate "Last admin note" column
- Defensive checks for gravity api calls
- Add "Last Admin Note" and "Last Admin Active" to order details page
- Add "Code" to order details page
@ashkan18 let me know if you'd like me to start round robining these PR's to other people!

More exchange admin overview changes

---

app/admin/orders.rb

* Remove unneeded `:order`
* Remove trailing whitespace

Small cleanups on admin active DSL

---

config/initializers/datadog_statsd.rb

I'm not sure how this happened, but I got a green build on #235 so I merged it and then it failed on master because of a couple RuboCop things. This PR fixes those violations.
@ashkan18 please take a look at the changes I made to the creation of that statsd thingy - RuboCop was complaining about the formatting there, so I just broke off the building into a separate method - how does that look to you?

Fix RuboCop

---

app/services/order_approve_service.rb
app/services/order_cancellation_service.rb

Track money

---

app/admin/orders.rb
app/services/gravity_service.rb
spec/services/gravity_service_spec.rb

Changes in this PR:
- New call to gravity to get user info
- Display user info alongside shipping info
- Populate email field
- Add gravity service spec for new call

Get proper buyer info

---

app/services/order_submit_service.rb

track order submit

---

hokusai/development.yml

bind to 0.0.0.0 for dev

---

README.md
dangerfile.ts

Added a danger rule for warning people when they add/update models. 
@orta i was wondering it would be nice if we could automatically label PRs with something like `notifyAnaltics` label or something, but now sure how to do that.

Update Readme and new danger rule

---

app/events/order_event.rb
app/events/transaction_event.rb
spec/events/order_event_spec.rb
spec/events/transaction_event_spec.rb

Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-624

Add order.mode to posted events

---

_schema.graphql
app/graphql/types/offer_type.rb
spec/controllers/api/requests/order_my_offer_request_spec.rb

Follow up on #286 to add `shippingTotalCents` and `taxTotalCents` on `offer` type.

Expose transactionTotalCents and shippingTotalCents in offerType

---

app/events/order_event.rb
app/events/transaction_event.rb
app/graphql/mutations/approve_order.rb
app/graphql/mutations/base_mutation.rb
app/graphql/mutations/seller_accept_offer.rb
app/jobs/post_order_notification_job.rb
app/services/offers/accept_service.rb
app/services/offers/submit_order_service.rb
app/services/order_approve_service.rb
app/services/order_cancellation_service.rb
app/services/order_service.rb
app/services/order_submit_service.rb
spec/controllers/api/requests/approve_order_mutation_request_spec.rb
spec/controllers/api/requests/confirm_pickup_request_spec.rb
spec/events/order_event_spec.rb
spec/events/transaction_event_spec.rb
spec/jobs/post_notification_job_spec.rb
spec/services/offers/accept_service_spec.rb
spec/services/offers/submit_order_service_spec.rb
spec/services/order_approve_service_spec.rb
spec/services/order_cancellation_service_spec.rb
spec/services/order_service_spec.rb
spec/services/order_submit_service_spec.rb

Do not merge as I'm still doing some manual integration testing, but I expect that this PR is complete
TODO:
https://artsyproduct.atlassian.net/browse/PURCHASE-660

Notify when offer is approved

---

app/graphql/mutations/submit_order.rb
app/graphql/mutations/submit_order_with_offer.rb
app/services/offers/submit_order_service.rb
app/services/order_approve_service.rb
app/services/order_cancellation_service.rb
app/services/order_service.rb
app/services/order_submit_service.rb
spec/services/offers/submit_order_service_spec.rb

Follow up and waiting on https://github.com/artsy/exchange/pull/295

Rename `by` argument to `user_id`

---

app/models/fulfillment.rb
app/models/line_item.rb
app/models/offer.rb
app/models/transaction.rb

Revert "Add Papertrail to few other models"

---

README.md

Links to an annotated guide on how to add MP operations. I didn't add it to the doc since this is temporary until we implement stitching.

Howto add MP operation guide

---

spec/controllers/api/requests/offers/reject_offer_mutation_request_spec.rb

Fixes a spec broken in https://github.com/artsy/exchange/pull/325

Fix broken spec

---

app/graphql/types/query_type.rb
spec/controllers/api/requests/orders_query_request_spec.rb

context: https://artsy.slack.com/archives/C9YNS4X32/p1544717508306600
fixing this: https://sentry.io/share/issue/6a2a09d7e2dc49baae2841cbdba5a794/

`orders` optional argument

---

_schema.graphql
app/jobs/order_follow_up_job.rb
app/models/order.rb
app/services/order_cancellation_service.rb
spec/jobs/order_follow_up_job_spec.rb
spec/services/order_cancellation_service_spec.rb

Addresses [SELL-1244](https://artsyproduct.atlassian.net/browse/SELL-1244)
Adds `buyer_lapse` action to `Order` and `OrderFollowUpService`

Adds buyer_lapse order action and follow-up-job

---

app/events/offer_event.rb

Follow up on comments in #338 and https://github.com/artsy/pulse/pull/323
cc: @starsirius

Follow up on offer event PR

---

app/graphql/mutations/buyer_counter_offer.rb
app/graphql/mutations/seller_counter_offer.rb
app/services/offer_service.rb
lib/offer_order_totals.rb
spec/services/offer_service_spec.rb

Code review comments follow up on #346

---

app/admin/orders.rb

https://artsyproduct.atlassian.net/browse/SELL-1280

Sell-1280, remove unused filters, add submitted and completed

---

app/admin/orders.rb
app/helpers/admin_helper.rb
config/initializers/active_admin.rb

Add offer support to admin order details page
https://artsyproduct.atlassian.net/browse/SELL-1281

[Active Admin] Order Details Changes

---

app/admin/orders.rb

Added `Type` to Order details section

Admin Followup to add type to order details

---

_schema.graphql
app/graphql/types/line_item_type.rb
app/graphql/types/query_type.rb
spec/controllers/api/requests/line_items_query_request_spec.rb

Fixes [SELL-1343](https://artsyproduct.atlassian.net/browse/SELL-1343)
**TODO:**
Sample query:
```graphql
query ($artworkId: String,  $states: [OrderStateEnum!]) {
lineItems(artworkId: $artworkId, orderStates: ['SUBMITTED', 'PENDING'] ) {
edges {
node {
id
listPriceCents
artworkId
artworkVersionId
editionSetId
order {
code
state
}
}
}
}
}
```
Response:
```json
{
"data": {
"lineItems": {
"edges": [
{
"node": {
"id": "e78710de-3b62-4b9d-addd-8a6661353daf",
"listPriceCents": 40000,
"artworkId": "5bcf8995b75dd13e0a1b3091",
"artworkVersionId": "5bfb2abb84b2f5727a317f52",
"editionSetId": null,
"order": {
"code": "469591585",
"state": "SUBMITTED"
}
}
},
{
"node": {
"id": "820d3b03-19d8-4295-ae88-e8931c02cbb6",
"listPriceCents": 40000,
"artworkId": "5bcf8995b75dd13e0a1b3091",
"artworkVersionId": …
```

Add query line items by artwork id

---

spec/services/order_submit_service_spec.rb

Currently we rescue from validation errors during commit process, which looking at the code at the first look it seemed we are then undeducting the inventory without deducting it
https://github.com/artsy/exchange/blob/f30f86c4a7cb7605611a43d8495a760aace6ffca/app/services/commit_order_service.rb#L20
This is not going to happen since on `undeduct_inventory` method we will only try to call Gravity for the line items that we have deducted inventory on them.
https://github.com/artsy/exchange/blob/f30f86c4a7cb7605611a43d8495a760aace6ffca/app/services/commit_order_service.rb#L43
In case of validation error, the list of deducted inventory will be empty so we are safe
Added a spec to verify ☝️

spec for making sure we don't undeduct inventory if validation fails

---

db/migrate/20190115140317_add_shipping_total_cents_to_line_items.rb

follow up on #354 where migration failed updating line items.

Fix migration and log weird cases

---

db/migrate/20190115140317_add_shipping_total_cents_to_line_items.rb

Check for 0 line items as well, verified this is not an issue on prod but still makes sense to fix for staging.

Follow up on followup migration

---

app/admin/orders.rb

Add Buyer Reject action to order admin page

Add Buyer Reject button to admin actions

---

app/admin/orders.rb

For https://artsyproduct.atlassian.net/browse/GALL-1387

Show note in exchange admin order details page

---

app/graphql/types/query_type.rb
spec/controllers/api/requests/order_query_request_spec.rb
spec/controllers/api/requests/orders_query_request_spec.rb

Exact revert of https://github.com/artsy/exchange/pull/280
Tests pass. This is the exchange side of https://artsyproduct.atlassian.net/browse/GALL-1369
See the volt/cms side here: https://github.com/artsy/volt/pull/3427

Add back sales admin privs

---

app/models/order.rb

I'm not sure if any of you like this but in case you do...
* `orders.id != ?` could be replaced with `.where.not(id: ...)`
* `orders.state = ?` could be replaced with `.where(state: SUBMITTED)`

Use more relation methods to make it (maybe) a bit easier to understand

---

app/admin/orders.rb
app/models/order.rb

This ActiveAdmin thing is deep magic ✨

Add has_offer_note filter to admin interface

---

config/initializers/datadog.rb

following https://github.com/artsy/gravity/pull/12240

Disable datadog in console

---

app/admin/orders.rb

Remove approve order button when order is not BN.
Add accept offer button for submitted offer orders.
fixes: https://artsyproduct.atlassian.net/browse/PURCHASE-1039

Add Accept Offer Button

---

app/admin/orders.rb
app/assets/stylesheets/active_admin.scss
app/models/offer.rb
spec/models/offer_spec.rb

- format things better
- add an event for accepting an offer

PURCHASE-1079 Admin can see event for offer accepted in "Negotiation" section of exchange admin

---

lib/buy_order_totals.rb
lib/order_shipping.rb
spec/scenario/reset_shipping_request_spec.rb

https://artsy.slack.com/archives/CB110C6LE/p1558627040005300
Follow 👇 going to first add a failing spec, describe the issue and then commit fixes.

[WIP] Fix not recalculating shipping fees after changing fulfillment

---

spec/integration/make_offer_happy_path_spec.rb
spec/support/offer_query_helper.rb
spec/support/query_helper.rb

__Steps:__
- Buyer creates offer
- Adds shipping
- Adds payment
- Submits
- Seller accepts offer
- Seller fulfills offer

PURCHASE-1134: "Happiest path" test in Exchange for the Make Offer flow

---

.circleci/config.yml
README.md

- Updates `config.yml` to use hokusai orb

Updates config to use orb

---

hokusai/production.yml
hokusai/staging.yml

~~HOLD while waiting on https://github.com/artsy/exchange/pull/419 for automatic config updates~~
- Uses named variables for ports (https://docs.google.com/document/d/1i0P_wOQ7cY_2AmFvy5zV5hiQg6BDgL4m9RjhKCaL33E/edit )

Updates hokusai ports in staging and production

---

hokusai/production.yml
hokusai/staging.yml

Fixes some indentation errors causing YML to fail on update - https://circleci.com/gh/artsy/exchange/2279

Fix YML indentation

---

hokusai/production.yml
hokusai/staging.yml

- Adds nginx container to staging and production
- Adds missing `affinity` blob to staging

Use nginx sidecar container

---

lib/payment_service.rb
spec/support/stripe_helper.rb

Discussion (hmm... or more like Monolog) here https://artsy.slack.com/archives/C9YNS4X32/p1565635031042300
going to self-merge

Fixed checking for wrong payment intent state after SCA

---

spec/integration/make_offer_sca_happy_path_spec.rb

fixes
https://circleci.com/gh/artsy/exchange/2520

Fix test broke because of famous copy/paste

---

app/admin/orders.rb
app/helpers/admin_helper.rb

Reopening this for now with the version that I already had.
@joeyAghion - we agreed to place the ticket for replacing this with gravity's money_helper at the time we start adding more things here.

support display of pounds

---

app/graphql/types/query_type.rb
lib/artsy_auth_token.rb

Exchange admin is broken after #501, issue is we expect user roles to be an array but it's string.
going to #mergeongreen it
cc: @jonallured @starsirius

Fix issue with admin auth

---

app/admin/orders.rb
app/events/transaction_event.rb
spec/events/transaction_event_spec.rb

[Deploy] Add missing event fields

---

app/admin/fraud_reviews.rb
app/admin/orders.rb
db/migrate/20200129000433_rename_fraud_flag.rb
db/schema.rb

I talked to Caroline about this a little more and we decided to simplify the naming scheme.

rename consider_fraudulent to flagged_as_fraud

---

spec/support/gravity_helper.rb

Part of a long list of updates surrounding the deprecation of invoicing... https://artsyproduct.atlassian.net/browse/GALL-2281

Remove reference to deprecated payments_enabled partner field

---

hokusai/test.yml

See https://github.com/artsy/rosalind/pull/349 and https://artsy.slack.com/archives/CP9P4KR35/p1581717280251400

fix failing CI build

---

app/helpers/admin_helper.rb
app/models/order.rb
spec/models/order_spec.rb

This PR adds the Euro as a supported currency for orders.

Support Orders for Artworks Listed in Euros (GALL-2642)

---

README.md

Removes coveralls badge and replaces with codecov.

#trivial Use codecov badge

---

README.md

Per this thread I'm just updating the point people on this repo:
https://artsy.slack.com/archives/CA8SANW3W/p1587410546406900

Update point people

---

hokusai/production.yml
hokusai/staging.yml

Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2522

add MALLOC_ARENA_MAX, add DD_TRACE_AGENT to sidekiq

---

hokusai/production.yml
hokusai/staging.yml

https://artsyproduct.atlassian.net/browse/PLATFORM-2744
True up with hokusai templates:
https://github.com/artsy/artsy-hokusai-templates/blob/ac33c4db8754143318612497f68361b64ea1abd6/default/hokusai/production.yml.j2#L99
Change node affinity from `preferred` to `required`.

Update node affinity.

---

db/migrate/20210115162614_add_impulse_conversation_id_index_to_orders.rb
db/schema.rb

Adds conversation id to order table to associate an order with a conversation.
cc @artsy/purchase-devs 
https://artsyproduct.atlassian.net/browse/PURCHASE-2345

chore: Adds impulse conversation id column
