app/controllers/application_controller.rb, app/graphql/mutations/create_order.rb, hokusai/production.yml, hokusai/staging.yml, spec/support/auth_helper.rb
User id comes in `sub` in our token while we were looking for `id`. 
Also use port 80 for the app.
=> Fix auth to use sub for user id and switch to port 80 on k8s

app/graphql/types/order_type.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb
Support query by partners based on user's jwt token and more spec.
Also as part of this, we replaces usages of `[]` for returning array of things to `connection_type` so now `orders` query returns a `connection` which means we now support all connection related pagination support and also we need to get the results using `edges` and `node`.
https://dev-blog.apollodata.com/explaining-graphql-connections-c48b7c3d6976
=> Add spec for orders query

app/graphql/mutations/submit_order.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb
Removing shipping info from submit order mutation until we have clarity around what data we want and how it should be stored.
=> Remove shipping info from submit order mutation

config/environments/production.rb, hokusai/production.yml, hokusai/staging.yml
- `force_ssl` on staging and production.
- Add SSL support to k8s setting.
- Add sidekiq service
https://artsyproduct.atlassian.net/browse/CP-58
=> Force ssl on staging and prod, also add sidekiq service

app/graphql/types/order_state_enum.rb, app/graphql/types/order_type.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/finalize_order_mutation_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb
Currently `state` in our GraphLQ schema is just a good old `String` and doesn't have any validation.
Switch to use [GraphQL Enum](http://graphql-ruby.org/type_definitions/enums) for order states.
=> Use GraphQL enum for order states

README.md, dangerfile.ts
With https://github.com/artsy/metaphysics/pull/1120 in the works, we need to make sure everytime we update Exchange's GraphQL schema, we need to update the copy of it stored in Metaphysics.
We [already added](#41 ) a danger rule to make sure it warns people if they've changed the schema, here we added some documentation about what needs to be done and updated danger file to point to this new doc.
=> Update README to reflect graphql schema changes

app/graphql/types/line_item_attributes.rb, app/graphql/types/line_item_type.rb, app/services/line_item_service.rb, db/migrate/20180621193842_add_quantity_to_line_items.rb, db/schema.rb, spec/controllers/api/requests/create_order_mutation_request_spec.rb, spec/fabricators/line_item_fabricator.rb, spec/services/line_item_service_spec.rb
[CP-59](https://artsyproduct.atlassian.net/browse/CP-59)
Adds `quantity` to line items as a non-null field that defaults to 1 in the database. Required field for `LineItemAttributes`. We might change this later to be non-required for attributes and default to 1.
=> Add quantity to line items

hokusai/config.yml, hokusai/production.yml, hokusai/staging.yml
We noticed Sidekiq on k8s was in crashloop and wasn't starting with following error:
```
2018-06-21T10:28:45.976Z 1 TID-gov2ckjxt INFO: Running in ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
2018-06-21T10:28:45.976Z 1 TID-gov2ckjxt INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-06-21T10:28:45.976Z 1 TID-gov2ckjxt INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-06-21T10:28:45.977Z 1 TID-gov2ckjxt INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-1", :url=>"redis://staging-shared.uvuuuk.0001.use1.cache.amazonaws.com/7"}
2018-06-21T10:28:45.981Z 1 TID-gov2ckjxt INFO: Starting processing, hit Ctrl-C to stop
2018-06-21T10:28:50.934Z 1 TID-gov2ckjxt INFO: Shutting down
2018-06-21T10:28:50.934Z 1 …
```
=> Fix Sidekiq restart issue

app/graphql/types/line_item_type.rb, app/graphql/types/order_type.rb
`updated_at` was called `update_at` and added `updated_at` and `created_at`
=> Fix typo in update_at and add updated_at and created_at to line items

app/graphql/types/order_type.rb, app/graphql/types/query_type.rb, app/models/order.rb, db/migrate/20180625123034_remove_item_total_cents_from_orders.rb, db/schema.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
- Remove `item_total_cents` from `Order` and instead calculate it based on the Order's line items.
- Expose `items_total_cents`, `shippint_total_cents`, `tax_total_cents`, `comission_total_cents`  and `transaction_fee_cents` in the schema.
- added spec for `order(id: ID!)` query
=> Remove itemsTotalCents from schema, add as a field on order

app/models/order.rb, app/services/order_service.rb, spec/controllers/api/requests/create_order_mutation_request_spec.rb
fixes https://github.com/artsy/exchange/issues/47
We added new `abandon` action to `Order`. Now when we create order, we first check if there are any _pending_ orders we abandon them and then we create the order.
=> Relax createOrder mutation

app/graphql/types/order_type.rb, app/models/order.rb, db/migrate/20180702162920_add_state_updated_expires_at_to_orders.rb, db/schema.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/models/order_spec.rb
In CMS UI we want to be able to show when the current state (if) expires.
Added `state_updated_at` and `state_expires_at` fields to reflect when order state was updated and whats the current expiry, knowing that not all states may expire, this field 
Keep in mind, currently we don't know exactly which states are going to expire and what is the threshold but for now setting two states with some basic thresholds.
cc: @sepans @jonallured
=> Add `state_updated_at` and `state_expires_at`

app/graphql/types/order_type.rb, app/models/order.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/models/order_spec.rb
We were calculating total and subtotal in CMS. We want to have one source of truth for totals and subtotals and it makes sense for that to be Exchange since it's the place that will ultimately calculate these values and call Stripe with that for holding the charge.
Add `totalCents` and `subtotalCents` to `Order` and `OrderType`.
Add these to MP.
=> Add totalCents and subtotalCents

app/graphql/mutations/set_payment.rb, app/models/order.rb, app/services/order_service.rb, app/services/payment_service.rb, app/services/transaction_service.rb, db/migrate/20180716171451_remove_merchant_account_id_from_orders.rb, db/schema.rb, spec/controllers/api/requests/set_payment_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/order_service_spec.rb, spec/services/payment_service_spec.rb
- Removes `merchant_account_id` from `order` model and `submitOrder` mutation
- Fetches `merchant_account_id` directly from Gravity
=> Fetch merchant_account_id directly from Gravity

app/services/order_service.rb, spec/controllers/api/requests/create_order_mutation_request_spec.rb
Current pending order validation is expensive and doesn't really provide much, After some discussions, it seems the easiest solution for now would be to always create new order regardless of existing pending orders. This is fine since all subsequent mutations work with `order` id and they should be fine. 
Always create new orders and don't even check for existing orders.
We will be creating pending charges but they can be cleaned up in many ways by queuing jobs or daily task that cleans up old pending orders.
=> Create new order all the time

README.md, app/graphql/mutations/create_order.rb, db/schema.rb, spec/controllers/api/requests/create_order_mutation_request_spec.rb
Use user id in JWT for creating the order. This makes things easier on client side and follows existing patterns used for other mutations.
=> Remove required userId in createOrder

config/application.rb
`net/http` is available in dev but not in production, possibly due to how rails loads files in each environment. Adds `net/http` to application config to fix this difference.
=> Require 'net/http' in application config

README.md, app/graphql/mutations/set_shipping.rb, app/services/order_service.rb, db/migrate/20180718174508_add_shipping_region_to_orders.rb, db/schema.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
This came up during mock-pilot, we were missing `shipping_region` on Order. Adding it in this PR.
=> Add shipping region

app/models/order.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/models/order_spec.rb
After approving an order, `state_expires_at` timestamp doesn't get updated properly and it becomes nil.
fixes #69 
In the state expiry setting we didn't have approved since we didn't know whats the expiration rule.
Set expiry for 5 days for _approved_.
=> Fix approved state expiration timestamp issue

app/services/order_submit_service.rb, app/services/payment_service.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/order_submit_service_spec.rb, spec/services/payment_service_spec.rb
**Before**: The supplied `credit_card_id` from `setPayment` mutation was passed directly to the Stripe charge object as the `source`.
**With these changes**: The supplied `credit_card_id` is used to look up the user's Stripe credit card ID in Gravity, which is then passed to the charge object as the `source`.
**What changed**:
- Fetches buyer's Stripe credit card ID from Gravity using supplied `credit_card_id` on order submit and uses in transaction
- Adds `customer_id` to Stripe charge object since we need to use it for saved credit cards
- Refactors `PaymentService.authorize_charge` to use keyword arguments as parameters
=> Fetch Stripe credit card ID from Gravity on order submit

app/services/order_submit_service.rb, db/migrate/20180719184045_add_external_charge_id_to_orders.rb, db/schema.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/order_submit_service_spec.rb
We would authorize a charge and save the transaction on order submit but not store the charge id on the order model itself. Since an order may have multiple charges, we would have to decide which transaction ought to be captured in order to complete the order.
The order model now contains an `external_charge_id` field that stores the Stripe charge id of the charge created on submitting an order. This allows us to easily retrieve it later when we want to capture the charge.
- Adds `external_charge_id` string field to `orders` table
- Saves Stripe charge id to `external_charge_id` on successful submission of an order.
=> Add `external_charge_id` to Order model and save on order submit

Gemfile, Gemfile.lock, app/models/transaction.rb, app/services/order_service.rb, app/services/order_submit_service.rb, app/services/payment_service.rb, app/services/transaction_service.rb, db/migrate/20180719203953_add_captured_to_transactions.rb, db/migrate/20180723192428_add_transaction_type_to_transactions.rb, db/schema.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/payment_service_spec.rb, spec/support/use_stripe_mock.rb
- Adds `PaymentService.capture_charge`, which retrieves a Stripe charge by id and captures it.
- Captures charge on order approval and records the successful (or failed) transaction.
- Adds Boolean `captured` column to `orders` to differentiate between captured and uncaptured charges.
- Adds `stripe-ruby-mock` to dependencies and refactors some tests to use mocked Stripe calls.
=> Capture charge on order approval

app/graphql/types/order_type.rb, spec/controllers/api/requests/set_payment_mutation_request_spec.rb
We want to be able to show last 4 digits and expiration on confirmation page and somewhere in CMS.
Expose `creditCardId` from Exchange so we can resolve it later in MP to actual details.
Update MP's schema with this change.
=> Expose Gravity's credit card id

app/services/order_submit_service.rb, lib/adapters/gravity_v1.rb, spec/services/order_submit_service_spec.rb
- Modifies `get_merchant_account` and `get_credit_card` to rescue `GravityError`s. If the error is a 404 raises a more informative error message.
- Checks that credit cards are not deactivated
- Moves merchant account / credit card data validation to `get_merchant_account` and `validate_credit_card` methods
- Adds `status` to `GravityError`
=> Add more careful error handling for fetching credit card and merchant account

app/graphql/types/order_state_enum.rb, spec/controllers/api/requests/order_query_request_spec.rb
When there are abandoned orders in the returning results, we get graphql errors rendering the response.
fixes #88 
We were missing matching enum for `ABANDONED` orders, add it.
=> Fix issue with returning abandoned state

.rubocop_todo.yml, README.md, app/graphql/mutations/finalize_with_one_fulfillment.rb, app/graphql/mutations/fulfill_at_once.rb, app/graphql/mutations/fulfill_with_one_fulfillment.rb, app/graphql/types/date_type.rb, app/graphql/types/fulfillment_attributes.rb, app/graphql/types/fulfillment_type.rb, app/graphql/types/line_item_type.rb, app/graphql/types/mutation_type.rb, app/graphql/types/order_state_enum.rb, app/models/fulfillment.rb, app/models/line_item.rb, app/models/line_item_fulfillment.rb, app/models/order.rb, app/services/order_service.rb, db/migrate/20180730173716_create_fulfillments.rb, db/migrate/20180730173943_create_line_item_fulfillments.rb, db/schema.rb, spec/controllers/api/requests/finalize_order_mutation_request_spec.rb, spec/controllers/api/requests/fulfill_at_once_request_spec.rb, spec/controllers/api/requests/fulfill_order_mutation_request_spec.rb, spec/models/fulfillment_spec.rb, spec/models/line_item_fulfillment_spec.rb
We started to introduce `Fulfillment` in #86  for tracking fulfillments per order. After some discussion we decided that the modeling could be better where we track fulfillment per `lineItem` instead of per order. 
Basically each line item can have many fulfillments (Imagine a big sculpture, or a line item with quantity more than one) and also each fulfillment could possibly handle multiple line items.
fixes #71 
Added `Fulfillment` and `LineItemFulfillment` which is the connection model between `LineItem` and `Fulfillment`.
A `LineItem` can have many `fulfillments` and a `Fulfillment` can have many `line_items`.
We talked about having two separate mutations for this possibly, one for adding fulfillments and one for finalizing order. While this seems to be the proper way overall, in order …
=> Add new mutation for finalizing orders with one fulfillment

.rubocop.yml, app/graphql/types/base_field.rb, app/graphql/types/base_object.rb, app/graphql/types/order_type.rb, spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb, spec/controllers/api/requests/order_field_permissions_spec.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/create_order_service_spec.rb, spec/services/order_submit_service_spec.rb
Current schema allows for clients to request all available fields, this is not the desired behavior since we don't want buyer to see seller specific fields like `transaction_fee_cents` and etc.
Used GraphQL Ruby's [Authorization](http://graphql-ruby.org/authorization/authorization) approach. We added `BaseField` in which:
- We added `buyer_only` and `seller_only` attributes which can be set on field definition
```ruby
field :seller_total_cents, Integer, null: true, seller_only: true
field :buyer_total_cents, Integer, null: true, buyer_only: true
```
- We added `authorized?` method to `BaseField` which is called by graphql ruby on every field being returned, current code only supports `buyer_only` and `seller_only` on `Order` type, but if needed we can add it to other Types too.
- In …
=> Limit access to fields

Gemfile, Gemfile.lock, app/services/gravity_service.rb, app/services/order_submit_service.rb, lib/adapters/gravity_v1.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/gravity_service_spec.rb, spec/services/order_submit_service_spec.rb
We want to calculate Transaction fee when an order is submitted.
We now calculate and set `transaction_fee_cents` on an order when order is submitted. This fee currently matches Stripe's US fee which would work for us as long as Partner's merchant account is setup in a US bank.
@williardx based on what we talked about before, i moved `get_merchant_account` and `get_credit_card` methods to `GravityService`, let me know what you think 👍
=> Transaction fee cents

README.md, app/services/shipping_service.rb, spec/services/shipping_service_spec.rb
https://artsy.slack.com/archives/CB110C6LE/p1533670813000231
We saw a `Cannot match against 'undefined' or 'null'.` error when using MP to set shipping for artworks without location. This makes it raise proper error with messages when location is missing.
Another case not addressed here is a location without country will be treated as international, given current implementation. Not sure if this will happen in Gravity but want to raise it here.
=> Raise error when calculating shipping for artwork without location

app/events/order_event.rb, app/models/order.rb, spec/events/order_event_spec.rb
This PR: 
- updates `OrderEvent` to use the more general 'ecommerce' `TOPIC` name I've been using in pulse
- adds a collected `shipping_info` object to the properties payload
- adds a `#to_s` method to prevent sending an ugly ruby object through amqp.
Tracked in https://artsyproduct.atlassian.net/browse/PURCHASE-369
=> add order data to rabbitmq event

app/services/create_order_service.rb, app/services/gravity_service.rb, app/services/order_submit_service.rb, db/schema.rb, lib/adapters/gravity_v1.rb, spec/services/create_order_service_spec.rb, spec/services/gravity_service_spec.rb, spec/services/order_submit_service_spec.rb
During BNMO demo we found our error handling for 404's from Gravity was not very robust or informative. This was partially because we raise a `GravityNotFoundError` in `GravityV1.request` and then end up rescuing it and re-raising a `GravityError`, leading to less helpful error handling.
Allow `GravityV1.request` to raise whatever errors it wants and let the methods that wrap it rescue errors with the correct error messages.
- Removes rescuing from `GravityV1.request`
- Adds rescues for `StandardError` in addition to `GravityError` for `GravityService` methods
- Adds error handling for `GravityService.fetch_partner`
- Adds tests to ensure that `GravityService` methods properly catch 404's
- Opportunistically adds a column that apparently wasn't previously committed to `schema.rb`.
=> Better error handling for Gravity requests

app/graphql/types/date_time_type.rb, spec/controllers/api/requests/order_query_request_spec.rb
In https://github.com/artsy/volt/issues/3117, we noticed that exchange doesn't return timestamps in ISO 8601, and that caused metaphysics to parse the time incorrectly and present wrong timestamps to clients.
This make `Types::DateTimeType` consistent to return timestamps in ISO 8601, as in Gravity.
=> Use ISO 8601 for DateTimeType

app/jobs/post_notification_job.rb, spec/jobs/post_notification_job_spec.rb
`PostNotificationJob#perform` calls `Events::OrderEvent#post`, but there is no `Events` namespace. As a result AMQP jobs are quietly retrying.
https://github.com/artsy/exchange/blob/4a38e435751b25553c5a5784a8e81ef0c48ea7ee/app/events/order_event.rb#L1
=> remove Events:: namespace from OrderEvent call

app/events/order_event.rb, app/graphql/mutations/set_shipping.rb, app/graphql/types/order_type.rb, app/models/order.rb, app/services/order_service.rb, db/migrate/20180815204249_add_shipping_name.rb, db/schema.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/events/order_event_spec.rb, spec/models/order_spec.rb
This PR addresses [PURCHASE-377](https://artsyproduct.atlassian.net/browse/PURCHASE-377), adding `shipping_name` to the Order db table and the various parts of the GraphQL schema.
~This PR is a work-in-progress because I have not yet tested it locally (but unit tests pass!).~
Here's it working in action:
Once this is merged, I will send a PR to metaphysics to update its copy of the Exchange schema.
=> Adds shipping name to db, GraphQL schema

app/services/order_service.rb, app/services/order_submit_service.rb
It's currently possible to enter a race condition and submit or approve an order twice, resulting in duplicate transactions and Stripe calls.
Lock the order when submitting or approving at the database level.
- Wrapped order submit and approve code in `order.with_lock`
- Created a method for constructing charge parameters  in `OrderSubmitService.submit!`, mostly to satisfy Rubocop.
=> Lock order before submitting or approving

app/graphql/types/order_type.rb
#minor but when orders are created, they won't have this field set (so we are getting errors on the initial mutation for a null field not being nullable).
=> @ashkan18 => allow shipping_name to be null in graphql schema

app/models/order.rb, app/models/transaction.rb, app/services/order_service.rb, app/services/order_submit_service.rb, app/services/payment_service.rb, app/services/transaction_service.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/services/order_service_spec.rb, spec/services/order_submit_service_spec.rb, spec/services/payment_service_spec.rb, spec/support/use_stripe_mock.rb
We need to refund a charge when an order is rejected.
On order rejection, create a new `Stripe::Refund` object with the order's charge ID and record the transaction.
- Adds `PaymentService.refund_charge` method, which takes in a Stripe charge ID and refunds it.
- Adds `PaymentService.refund_charge` to `OrderService.reject!` as well as a record of the refund transaction. The refund transaction stores the charge ID and the amount.
- Removes `TransactionService.create_success!` and `TransactionService.create_failure!` in favor of a single method `TransactionService.create!` that accepts a hash of the fields used in a transaction. Updates associated tests and code.
=> Refund charges for rejected orders

app/services/shipping_service.rb, spec/services/shipping_service_spec.rb
When `domestic_shipping_fee_cents` and `international_shipping_fee_cents` are not set we were assuming that means they are 0 but it actually means partner never confirmed/set the shipping cost on this artwork and we should raise error.
=> Raise error when missing shipping info

README.md, app/graphql/inputs/fulfillment_attributes.rb, app/graphql/inputs/shipping_attributes.rb, app/graphql/mutations/fulfill_at_once.rb, app/graphql/mutations/set_shipping.rb, app/graphql/types/fulfillment_union_type.rb, app/graphql/types/order_type.rb, app/services/order_service.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
There were some discussions started https://github.com/artsy/reaction/pull/1151/files/67bc80c99850925eafbad027eaf5daac9e76ae12#diff-58473875e67f62dffa8c78534cbfaa5e which lead to following decisions:
- Update `order` type to use a union for returning shipping related fields and basically don't return them for orders with `pickup` fulfillment type.
- In the union returned, remove redundant `shipping_` from all the fields now that we are already in a newly added `Ship` type
- Update `setShipping` mutation to wrap shipping related input fields under `shipping` so we can remove redundant `shipping_` from those fields and also have more structured data.
Basically do all the above. There are some weird looking code that needed to be added for this to work, i'll comment on those lines.
in your …
=> Refactor shipping related Mutations and Type

README.md, app/graphql/types/order_type.rb, app/graphql/types/requested_fulfillment_union_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
Because of MP's issues in using `requestedFulfilmentUnion` when getting a connection of `Order`s we reverted the changes we made in #119 and few followups.
We now have  a solution for that issue and can bring this back.
** COORDINATED MERGE ** going to open a MP PR to match these changes, lets merge this with that one around the same time so staging MP -> Exchange stays in sync.
=> [COORDINATED MERGE] Bring back requestedFulfillmentUnion

app/services/create_order_service.rb, spec/services/create_order_service_spec.rb
Fixes #138 
When creating an order, we set the state to pending but we don't set `state_expires_at` so https://github.com/artsy/exchange/blob/master/app/jobs/order_follow_up_job.rb#L6 fails.
Set it at order creation.
cc: @williardx
=> Fix compare to `nil` error

app/graphql/types/order_connection_with_total_count_type.rb, app/graphql/types/query_type.rb, config/database.yml, spec/controllers/api/requests/orders_query_request_spec.rb
https://artsyproduct.atlassian.net/browse/PLATFORM-835
From clients we sometimes want to show just the total count of specific query.
Added a custom connection type for our `Order` model which defines `total_count` field and used it in returning `orders` query. You can ask for `totalCounts` now on the same level as edges.
```graphql
query($sellerId: String, $buyerId: String, $state: OrderStateEnum, $sort: OrderConnectionSortEnum) {
orders(sellerId: $sellerId, buyerId: $buyerId, state: $state, sort: $sort, first: 2) {
totalCount
edges {
node {
id
}
}
}
}
```
In sample ☝️ we'll only get first 2 orders (note `first: 2` in the query)back but we'll get total count of all orders.
=> Add support for totalCount on orders

.rubocop.yml, app/graphql/types/order_type.rb, app/models/order.rb, app/models/state_history.rb, db/migrate/20180827150745_create_state_histories.rb, db/migrate/20180827151116_add_state_to_state_histories.rb, db/schema.rb, spec/models/order_spec.rb
This is a follow up PR for https://github.com/artsy/exchange/pull/124, where we decided to create a new `StateHistory` model to keep track of the entire history of an order's state changes.
Addresses [PLATFORM-773](https://artsyproduct.atlassian.net/browse/PLATFORM-773).
- Adds `StateHistory` model that's associated with `Order` for tracking state changes in an order. 
- On order creation and after every order action (submit, approve, reject, etc.) a new `StateHistory` record is created that records the time at which the order entered that state.
- Creates `submitted_at` and `approved_at` methods on `Order` that query `StateHistory` for the time at which an order became submitted and approved, respectively.
Metaphysics PR forthcoming.
=> Track order state history

lib/adapters/gravity_v1.rb, spec/services/order_submit_service_spec.rb
Fixes https://github.com/artsy/exchange/issues/137
When getting inventory error, we would only get something like:
```
Couldn't perform request! status: 400
```
Gravity errors have body and we can pars the response and return the message.
=> Show better error messages when getting errors from Gravity

config/database.yml
this was result of me trying to use staging db, for local we can hardcode it back to `exchange_development`
=> Bring back exchange_development

app/graphql/mutations/approve_order.rb, app/graphql/mutations/fulfill_at_once.rb, app/graphql/mutations/reject_order.rb, app/graphql/mutations/set_payment.rb, app/graphql/mutations/set_shipping.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/fulfill_at_once_request_spec.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/controllers/api/requests/set_payment_mutation_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
We've changed how we handle errors for mutation in #93 for create order mutation and we have #128 that does the same for `submitOrder`. This PR does the same thing for rest of the mutations.
This is a breaking change and need MP follow up.
=> Follow new style mutations for rest of mutations

app/graphql/types/order_type.rb, app/models/order.rb, spec/models/order_spec.rb
Followup from https://github.com/artsy/exchange/pull/134#discussion_r213509183, this a quick update to rename `submitted_at` -> `last_submitted_at` and `approved_at` -> `last_approved_at` to return the most recent timestamps at which the order entered those states. Also adds new helper method `get_last_state_timestamp`.
=> Rename and change submitted_at and approved_at to fetch last timestamp order entered those states

app/services/create_order_service.rb, spec/services/create_order_service_spec.rb
Still seeing issues with `pending` orders not having `state_expires_at` and `state_updated_at`, adding more spec around this and also possible fix.
=> Set stateUpdatedAt on newly created orders

app/graphql/mutations/set_shipping.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
We get `ArgumentError (missing keyword: phone_number):` when we don't pass `phone_number` as an input argument to `setShipping` mutation, this arg is optional and is ok to not have it in input.
Set the default to `nil` in the `resolve` method and add spec for checking that.
=> Make sure phoneNumber is not a required argument in the method

.rubocop.yml, app/jobs/record_sales_tax_job.rb, app/models/line_item.rb, app/services/order_service.rb, app/services/sales_tax_service.rb, app/services/shipping_service.rb, db/migrate/20180830165044_add_sales_tax_cents_to_line_items.rb, db/schema.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/services/order_service_spec.rb, spec/services/sales_tax_service_spec.rb, spec/services/shipping_service_spec.rb
We need to collect and remit taxes for orders shipping to or being picked up in NJ, WA or PA.
On order approval (and after charge capture) for NJ, WA or PA orders, post a transaction to TaxJar for each line item in the order that records the amount of sales tax we collected.
We post a transaction for each _line item_ and not for the whole order because it's possible for line items to be taxed differently. An order for pickup is taxed based on the location of the artwork, and if there are multiple line items in different locations then each line item will be taxed differently.
- Follows up on https://github.com/artsy/exchange/pull/91#discussion_r212501874 and reorganizes code as a class centered on the line item instead of a module centered on the order. Updates all corresponding specs.
- …
=> Post transaction to TaxJar on successful order approval and refactor SalesTaxService

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/sentry_raven.rb
This PR enables Sentry error reporting. I've already created [exchange-production](https://sentry.io/artsynet/exchange-production/) and [exchange-staging](https://sentry.io/artsynet/exchange-staging) projects in Sentry and set ENV variables (`ENV['SENTRY_DSN']`) to both staging and production. All we have to do is to just merge and deploy :)
=> Adds Sentry

app/services/payment_service.rb
Getting 👇 when trying to submit an order
```
F, [2018-09-06T13:22:52.404226 #6] FATAL -- : [f40da4e0-b1d7-11e8-84cb-e9e6b0b75015] NoMethodError (undefined method `account' for "acct_14FIYS4fSw9JrcJy":String):
F, [2018-09-06T13:22:52.404353 #6] FATAL -- : [f40da4e0-b1d7-11e8-84cb-e9e6b0b75015]
F, [2018-09-06T13:22:52.404436 #6] FATAL -- : [f40da4e0-b1d7-11e8-84cb-e9e6b0b75015] app/services/payment_service.rb:16:in `authorize_charge'
```
When writing tests, noticed we can get destination account using `charge.destination.account` but it seems that doesn't work in real world and we can get that basically from `destination.account` which is the account id.
=> Fix calling account on charge.destination

app/services/sales_tax_service.rb, spec/services/sales_tax_service_spec.rb
- Updates `record_tax_collected` so that we don't attempt to record a sales tax transaction for a line item that didn't have sales tax
- Updates the TaxJar order/transaction id to be `order_id-line_item_id` so that it's easier to map TaxJar transactions to orders.
=> Small sales tax follow up fixes

app/services/create_order_service.rb, app/services/order_service.rb, app/services/order_submit_service.rb, app/services/order_total_updater_service.rb, spec/services/order_service_spec.rb, spec/services/order_submit_service_spec.rb, spec/services/order_total_updater_service_spec.rb
We were not calling update totals before submission, we were setting commission and transaction fees and were missing updating totals after that which would lead to calling stripe and not holding commission and transaction in our account.
Totals were calculated in 2 different places, moved all of them into one service which can get commission rate as an input and based on that calculates all the totals of an order in one place! this makes things little more sane... hopefully.
=> OrderTotalUpdaterService

app/services/order_service.rb, app/services/order_total_updater_service.rb, app/services/sales_tax_service.rb, db/migrate/20180906205600_add_should_remit_sales_tax_to_line_items.rb, db/schema.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/services/order_total_updater_service_spec.rb
`order.seller_total_cents` currently doesn't subtract out taxes that Artsy is obligated to remit.
In addition to the sales tax for each line item, keep track of whether or not Artsy needs to remit the sales tax. Include the remittable taxes when calculating `seller_total_cents`.
- Adds a new Boolean field `should_remit_sales_tax` on `line_items` that's set by `SalesTaxService.artsy_should_remit_taxes?` when we calculate sales tax.
- Sums sales tax to be remitted and subtracts it out in `seller_total_cents`.
=> Include sales tax when calculating `seller_total_cents`

app/models/order.rb, spec/models/order_spec.rb
Our human-readable order code is currently sequential and based on the order id, which gives away information about our orders.
Generate a randomized human-readable order code.
- The code is now a 0-padded 9-digit integer.
- `update_code` checks the database to ensure the code is unique and will attempt to set the code 10 times before giving up and throwing an error.
=> Randomize order codes

app/services/gravity_service.rb, config/environments/production.rb, spec/spec_helper.rb
Originally we decided to cache Partner and Artwork data, but as we started testing, looks like caching mostly causes issue and leads to us using stalled data. We want to make sure we are using latest version of all these models when calling our main API.
Remove caching.
De-provision Memache instances assigned to Exchange.
=> 👋 Memcache and Cache

app/controllers/api/health_controller.rb, spec/controllers/api/health_controller_spec.rb
Adding `worker_health` to our health endpoint response, based on our threshold it either returns `OK` or `OY`
=> Add Sidekiq check to our health endpoint

app/graphql/types/requested_fulfillment_union_type.rb, app/services/order_shipping_service.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
Currently setting order requested fulfillment to Pickup on staging fails with address validation. Follow up on #175 
We are validating `shipping` input even if type is pickup, clients are currently sending `region: ''` and that fails checking region requirements.
Don't set/validate shipping address for pickup orders.
=> Fix setShipping to pickup issue

app/controllers/concerns/error_handler.rb, app/controllers/errors/application_error.rb, app/controllers/errors/error_types.rb, app/controllers/errors/internal_error.rb, app/graphql/types/application_error_type.rb, app/services/create_order_service.rb, app/services/gravity_service.rb, app/services/order_shipping_service.rb, app/services/order_submit_service.rb, spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb, spec/controllers/api/requests/error_handling_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/services/gravity_service_spec.rb, spec/services/order_submit_service_spec.rb
Added `Errors::ERROR_TYPES` as a Hash with keys being all current possible error `types` and each type has a list of possible `codes` for that type. On creating `ApplicationError` we check if type and code are valid. This way `Errors::ErrorTypes` should be our source of truth for all current errors.
In this PR we also updated root level errors to match [GraphQL specs](http://facebook.github.io/graphql/June2018/#example-fce18) where we are required to provide a `message` and we can add our own specific fields under `extensions`.
Used `Errors::InternalError` for things like Gravity's generic errors.
=> Mo error handling less problems

app/graphql/types/order_connection_sort_enum.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb
This PR adds the ability to sort the orders list by the `state_updated_at` timestamp. I started by adding it to the `Types::OrderConnectionSortEnum` and getting a red test. From there I added the code to get back to green which was just adding to the case statement that I found in `Types::QueryType#orders`, but it occurred to me that with a little extract method, I'd be able to support future sorting options that follow the format of `[attribute_name]_[direction]` so I did that with a894e3e. Along the way I also did some work on making the specs a little more consistent by extracting a helper to work with ids in the response data so that comparing them to the ids of fabricated data is easier.
I'm not sure if this is enough - I guess I need to update the schema and propagate that change to …
=> Sort by state updated at

app/services/sales_tax_service.rb, spec/services/sales_tax_service_spec.rb
Based on continuing conversations around sales tax with business and legal stakeholders, this removes NJ from the list of states where we should remit sales taxes.
=> Remove NJ from the list of states where we should remit sales taxes

app/controllers/errors/error_types.rb, app/services/create_order_service.rb, spec/services/create_order_service_spec.rb, spec/support/gravity_helper.rb
Make sure we raise error when artwork was:
- unpublished
- disabled for ecommerce
Updated https://www.notion.so/artsy/Error-and-failure-states-for-Orders-b3dfcdef33bc4f2b9a1f912568cb3c8e with the changes
=> More CreateOrder errors Raise error

app/controllers/concerns/error_handler.rb, app/controllers/errors/error_types.rb, app/controllers/errors/inventory_error.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb
We are getting 500 when artwork version mismatch is raised.
We were missing `artwork_version_mismatch` code in list of `error_types`  under `processing` errors.
Add it and also add a spec for it.
=> Missing error type for artwork version mismatch

app/controllers/errors/error_types.rb, app/graphql/mutations/confirm_pickup.rb, app/graphql/types/mutation_type.rb, app/services/order_service.rb, spec/controllers/api/requests/confirm_pickup_request_spec.rb
For pickup orders sellers need to confirm the work was picked up by the buyer. `fulfillAtOnce` is very specific and works for `SHIP` orders but not for `PICKUP`.
Added a new `ConfirmPickup` mutation which can be used only on pickup orders and all it does is it changes the order state to `fulfilled`.
```graphql
mutation($input: ConfirmPickupInput!) {
confirmPickup(input: $input) {
orderOrError {
... on OrderWithMutationSuccess {
order {
id
state
buyer {
... on Partner {
id
}
}
seller {
... on User {
id
}
}
}
}
... on OrderWithMutationFailure {
error {
code
data
type
}
}
}
}
}
```
=> Add `ConfirmPickup` mutation 

app/controllers/errors/error_types.rb, app/jobs/record_sales_tax_job.rb, app/models/order.rb, app/services/sales_tax_service.rb, db/migrate/20180927142906_add_sales_tax_transaction_id_to_line_items.rb, db/schema.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/models/order_spec.rb, spec/services/sales_tax_service_spec.rb, spec/support/taxjar_helper.rb
`RecordSalesTaxJob` was failing on pickup orders with unhelpful error messages.
- Refactor `RecordSalesTaxJob` to not try to create an address for pickup orders
- Add `tax_recording_failure` code to error types
- Store the transaction ID that we get back upon creating a transaction in TaxJar so that we can reference it later
- Adds string `sales_tax_transaction_id` to `line_items`
- Update `SalesTaxService` to store response from transaction POST request to TaxJar in `@transaction`
- Updates `line_item.sales_tax_transaction_id` after receiving transaction response from TaxJar
- Return early in `RecordSalesTaxJob` if sales tax does not need to be remitted
- Add method `shipping_address` to `Order` model that returns the shipping address wrapped in an `Address` object for shipped orders or …
=> Refactor RecordSalesTaxJob

app/controllers/concerns/error_handler.rb
As discussed in [this thread](https://artsy.slack.com/archives/CB110C6LE/p1538157819000100), we're adding exception logging to the `ErrorHandler` used to ensure GraphQL responses are returned.
<details>
<summary>Example logs from introducing an undefined variable and executing a request from MP</summary>
```
Started POST "/api/graphql" for 127.0.0.1 at 2018-09-28 15:15:39 -0400
(0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
↳ /Users/danielramirez/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/log_subscriber.rb:98
Processing by Api::GraphqlController#execute as */*
Parameters: {"operationName"=>"createOrderWithArtwork", "variables"=>{"artworkId"=>"5bad103ff748ad00074b475a", …
```
=> chore: log error message and stacktrace

app/controllers/errors/error_types.rb, app/graphql/mutations/create_order_with_artwork.rb, app/services/create_order_service.rb, spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb, spec/controllers/api/requests/error_handling_request_spec.rb, spec/services/create_order_service_spec.rb
Currently Eigen doesn't pass `edition_set_id` to `createOrderWithArtwork` mutation when there is one edition set. We need Exchange to check if artwork has only one edition set, assume that was the one that buyer meant to pick. In case there are more than one edition sets and `edition_set_id` was not passed, we now raise a new `validation` error with code `missing_edition_set_id`.
`CreateOrderService` was getting more complicated with these changes and as part of this change we did a little refactoring there where followed our new style. We now create a new instance of `CreateOrderService` and we call `process!` on it. We also expose created `order` with `attr_reader` on that class.
New edition set logic is:
- If `edition_set_id` was passed to the service
- we check if edition set exists …
=> More edition set handling

app/services/create_order_service.rb, spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
https://sentry.io/artsynet/exchange-staging/issues/706978737/?query=is:unresolved
With current logic if artwork's `edition_sets` is empty array we try to fetch first edition set and call `[:id]` on it which raises runtime error.
https://github.com/artsy/exchange/pull/198#pullrequestreview-160285287
use `present?` and do it earlier before calling `find_verify_edition_set`.
=> Fix empty array EditionSet issue

app/controllers/errors/error_types.rb, app/graphql/mutations/plain_mutation.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/order_query_request_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-496
We want to be able to find orders by code.
make `id` optional and add new `code` argument. Make sure one of them is required. 
type: `validation`, code: `missing_required_param`, data: `message: id or code is required`
=> Enable find Order by code

app/services/sales_tax_service.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/services/sales_tax_service_spec.rb
Legal has determined that we should not be remitting taxes sellers to any states right now. This may change in the future as legislation evolves.
Remove all states from `SalesTaxService::REMITTING_STATES` but keep code that allows us to remit sales tax to states.
- Removed WA and PA from `SalesTaxService::REMITTING_STATES`
- Updated specs
=> Remove all states from list of states where we need to remit taxes

app/controllers/errors/error_types.rb, app/graphql/types/application_error_type.rb, app/services/order_shipping_service.rb, lib/address.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/services/order_shipping_service_spec.rb, spec/services/sales_tax_service_spec.rb
As part of [PURCHASE-371](https://artsyproduct.atlassian.net/browse/PURCHASE-371), we want to validate against adding a non-continental US shipping address to an artwork with a nil `international_shipping_fee_cents` i.e. the work ships to continental us only. Exchange will return an error of type `invalid_shipping_address`, which reaction will use to display an appropriate modal. Reaction already disables the country field from being changed in this case, so this validation logic should only trigger when a user attempts to enter an address in Alaska or Hawaii.
This is the first time I've written Ruby in a while, so feel free to nit anything and everything.
=> Enforce domestic shipping only validation on adding address to order

app/services/order_cancellation_service.rb, spec/services/order_cancellation_service_spec.rb
We were still using `Order::SELLER_LAPSE` as event's action when calling post notification. That state was removed in previous PRs and was replaced with `Order::CANCELED`.
Switch to `Order::CANCELED` and add missing specs.
=> Stop using seller lapse for realZ

app/controllers/errors/error_types.rb, app/services/sales_tax_service.rb, spec/services/sales_tax_service_spec.rb
When we refund a captured charge we need to send a reversed transaction to TaxJar to record the refund if we previously collected sales tax and planned to remit it.
Add capability to create refund transactions in TaxJar. This will eventually be implemented in an async job in `OrderCancellationService`, but since we're not currently posting transactions to TaxJar I'm leaving it out for now. 
- Adds methods to handle creating refunds in TaxJar
- Refactors shared parameters for TaxJar API calls into a single method `construct_tax_params`
- Adds tests to ensure that we properly handle errors from TaxJar
=> Add ability to refund transactions from TaxJar

_schema.graphql, app/events/order_event.rb, app/graphql/types/base_field.rb, app/graphql/types/line_item_type.rb, app/services/order_total_updater_service.rb, db/migrate/20181003191806_add_commission_cents_to_line_items.rb, db/schema.rb, spec/controllers/api/requests/order_field_permissions_spec.rb, spec/events/order_event_spec.rb, spec/services/create_order_service_spec.rb, spec/services/order_total_updater_service_spec.rb
When creating `purchase` for each approved order in Gravity, we want to know the commission fee for each artwork sold. Currently `commission_fee_cents` is only stored on `Order`, this makes it hard for us to calculate the commission per artwork.
In general, it seems like a good idea to store `commission_fee_cents` on `LineItem` and also store the total on `Order` so we can go back and track what was the commission at the time of that order.
- Added `commission_fee_cents` to `LineItem`
- Updated `OrderTotalUpdater` to first set `commission_fee_cents` on `LineItem` and then set the total on `Order` based on `line_items`.
- For ☝️ , ended up locking the order to make sure totals are all set together now that updating line items is also involved.
- Updated `OrderEvent` to include …
=> Add commission_fee_cents to LineItem

app/services/order_shipping_service.rb
Fixes this [`NoMethodError`](https://sentry.io/artsynet/exchange-staging/issues/711632454/?query=is:unresolved) by checking the `fulfillment_type` of the order before validating the shipping location.
=> Guard validate_shipping_location with fulfillment type check

_schema.graphql, app/graphql/types/order_party_union_type.rb, app/models/order.rb, app/services/create_order_service.rb, app/services/order_submit_service.rb, spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb, spec/services/order_submit_service_spec.rb
For Auction Buy Now works, we want to use a different `type` for Stripe's `metadata` when creating charges.
https://artsyproduct.atlassian.net/browse/PURCHASE-547
Currently `seller_type` was hardcoded to be `partner`, we now make sure `seller_type` reflects the `partner[:type]` of the artwork. This way we store the partner type at the time of order on `Order` properly.
We use ☝️ to detect what should we send Stripe for `type` field of charge metadata. 
We also updated `OrderPartyUnion` to work with new cases of `seller_type` field.
```ruby
Order.update_all!(seller_type: 'gallery')
```
=> More generic `seller_type`

app/graphql/mutations/base_mutation.rb, app/graphql/types/query_type.rb, spec/events/order_event_spec.rb, spec/fabricators/order_fabricator.rb
After #220 was merged, we no longer have `seller_type` as `partner` and in `BaseMutation` when checking for user's access to order we were checking if `seller_type` is `partner` then check the `id`.
Check if `seller_type` is NOT `user` then check for partner id.
=> Fix broken seller mutations

app/graphql/types/order_type.rb, app/services/order_total_updater_service.rb, db/migrate/20181009163308_add_commission_rate_to_order.rb, db/schema.rb, spec/controllers/api/requests/order_query_request_spec.rb
Adds new fields to line item and exposes formatted display strings via GraphQL as part of [SELL-976](https://artsyproduct.atlassian.net/browse/SELL-976). Initial pass based off of discussions in Slack [here](https://artsy.slack.com/archives/CB110C6LE/p1539027899000100) and [here](https://artsy.slack.com/archives/CB110C6LE/p1539027970000100).
From the discussion [here](https://artsy.slack.com/archives/CB110C6LE/p1539026352000100), the current plan is to display the transaction fee as "3%" even though we calculate the fee using 2.9% + $0.30, and this may change in the future.
=> Add commission_rate and processing_fee_schedule to line item

app/models/order.rb, spec/models/order_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-564
Postal code is not mandatory for submitting an order.
Remove it from the list of mandatory shipping fields and add spec for it.
=> Make postal code optional

app/controllers/concerns/error_handler.rb, app/controllers/errors/auth_error.rb, app/controllers/errors/error_types.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-539
We decided a while back that users should receive 404 when trying to look at orders that they should not have access to. Users currently receive a 401 and this PR is changing it to 404 as intended. This is technically a breaking change, but I couldn't find any evidence of anyone relying on specific status codes. Certainly not from the reaction/force side. But would still be good to check about volt and etc
integration tested manually against metaphysics
=> Make :not_found return 404 instead of 401

_schema.graphql, app/graphql/types/order_connection_sort_enum.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb
As part of [SELL-1042](https://artsyproduct.atlassian.net/browse/SELL-1042), enable orders to be sorted over `state_expires_at`. This will enable Volt to sort its "Ready to Ship" tab to show the soonest to expire orders to the top.
=> Add Orders sorting over state_expires_at

app/events/transaction_event.rb, app/jobs/post_transaction_notification_job.rb, app/services/order_submit_service.rb, spec/events/transaction_event_spec.rb, spec/fabricators/transaction_fabricator.rb, spec/jobs/post_transaction_notification_job_spec.rb, spec/services/order_submit_service_spec.rb
CRT team wants to get notified every time a charge fails to get processed during BNMO checkout, similar to what they currently have in #fraud
Added a new `TransactionEvent`, for now only with `failed` as the only possible action. We call this now from the `ensure` block in submit order service only if transaction failed.
=> Post Events on Failed Charges

app/events/transaction_event.rb, spec/events/transaction_event_spec.rb
Add order `id` to `order` section in `TransactionEvent`.
Add it
=> Add order id to transaction events

app/services/sales_tax_service.rb, spec/services/sales_tax_service_spec.rb
The response from TaxJar may include taxes for jurisdictions other than states, but we _only_ want to consider state sales tax. This results in us potentially overcharging on sales tax.
If a tax breakdown from TaxJar is available (https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order), set the sales tax for that item to be the collectable amount for the state. Otherwise, if it's not available continue to use the overall `amount_to_collect`.
- Uses TaxJar's `breakdown` object to get the state tax collectable (if it's available) and sets sales tax to the state sales tax collectable.
- Adds line item details to the TaxJar parameters, which are required to get the `breakdown` object in the response.
=> Set item sales tax to be the collectable state sales tax when available

app/services/create_order_service.rb, app/services/order_submit_service.rb, config/initializers/datadog_statsd.rb
Only records 1 metric for now, order create. We can circle back and track lots of stuff once we verify this works.
=> enable statsd for exchange

app/admin/orders.rb
A method was renamed; we had one call that didn't get switched over to the new name. For now, we're just showing the first partner location returned by Gravity.
=> Call the appropriate GravityService method to get partner location info

README.md
I was unable to run the app locally until I had the appropriate security role assigned; this PR amends the docs to reflect this.
=> Amend docs to describe how to get access to Exchange

app/admin/orders.rb
Adds a confirmation dialog to the "Refund" button in the admin, so people don't accidentally refund orders.
Note: This PR does not include tests, because I don't really know how to add them for the admin. If anyone reviewing feels like they can help me with that, that would be grand. If not, we have another story for adding admin tests later (https://artsyproduct.atlassian.net/browse/PLATFORM-1021).
=> PLATFORM-977 - add confirmation dialog to “Refund” button in admin

app/services/base_create_order_service.rb, app/services/create_buy_order_service.rb, app/services/create_offer_order_service.rb, spec/controllers/api/requests/error_handling_request_spec.rb, spec/services/base_create_order_service_spec.rb, spec/services/create_offer_order_service_spec.rb
@zephraph had this awesome suggestion during our purchase team knowledge share about make it more obvious that `CreateOrderService` is actually our base class and implemented by offer and buy create order services.
Rename `CreateOrderService` to `BaseCreateOrderService`.
=> Rename CreateOrderService to BaseCreateOrderService

app/admin/orders.rb, app/helpers/url_helper.rb
For the context behind this change, please refer to the discussion on the Jira ticket below.
https://artsyproduct.atlassian.net/browse/PLATFORM-981
=> Remove Order status link from Order details page

app/controllers/api/base_api_controller.rb
Getting LOT of these warnings
```
Can't verify CSRF token authenticity.
```
in all of our API requests.
We've set
```
protect_from_forgery with: :null_session
```
in `BaseApiConroller` before which seems to allow calls without CSRF and just nullifies the session, but the warning message is still there!
Skip `verify_authenticity_token` in API controller all together!
I tried to do few other things like adding 👇 to main controller
```
protect_from_forgery unless: -> { request.format.json? }
```
which didn't work, I think we are safe with skipping this on API controllers, but let me know if you think otherwise.
=> Skip verify_authenticity_token for API endpoints

config/environments/production.rb
I noticed we're spouting debug-level logs from a bunch of systems including Exchange.
=> @yuki24: Don't log all SQL in prod

app/controllers/application_controller.rb, config/initializers/active_admin.rb, config/locales/en.yml
Pairing with @dleve123, we found a couple of configuration changes we could make so that the Exchange app **always** displayed times in the Eastern time zone, and with the time zone explicitly identified.
The previous iteration of this PR required us to manually convert to the eastern time zone any time we were displaying a date, which was cumbersome and easy to mess up. With the approach in this PR, we can be certain that every date rendered by Exchange will be in Eastern time, so we won't accidentally miss any.
In addition, we added the time zone abbreviation to times when they are displayed. This helps give clarity when some times are in Daylight time and some are in Standard time.
Once we changed to this approach, we decided that writing system tests didn't make sense, as they would …
=> Always display times in Eastern time, and with the timezone.

app/admin/orders.rb, app/controllers/api/health_controller.rb, app/models/order.rb, spec/models/order_spec.rb
Changes:
- Add two scopes, one for orders with "Case Closed" note, and another for orders with notes on them, but not "Case Closed"
- Add sorting ability based on Last Admin Action. This is how to join against a `has_many` association apparently, I'm not entirely sure how it works.
- Expand the `by_last_admin_note` scope to take an array of note types
- tests for `by_last_admin_note`
=> Filter admin actions, add ability to sort

Rakefile, _schema.graphql, lib/tasks/graphql.rake
If a developer forgets to run `rake graphql:schema:idl` and commit the
schema diff after changing GraphQL types, then `bundle exec rake` fails.
* Adds new `rake graphql:schema:diff_check`
* Adds new task as the first step of default Rake task
=> Add Rake task so that `bundle exec rake` fails when there's schema diff

_schema.graphql, app/graphql/types/offer_type.rb, db/migrate/20181108193631_add_submitted_at_to_offers.rb, db/schema.rb, spec/controllers/api/requests/order_query_request_spec.rb
Offers can be created without being submitted yet. We want to know about un-submitted offers and also we want to know when they are submitted.
Added `submitted_at` to `Offer` and expose it in the GraphQL response.
=> Add submitted_at to Offer

_schema.graphql, app/graphql/types/order_type.rb, spec/controllers/api/requests/create_offer_order_with_artwork_mutation_request_spec.rb
Follow up on comments in #273 , we don't have `items_total_cents` for offer orders till offer is added.
=> Relax items_total_cents requirement

app/services/gravity_service.rb, app/services/order_shipping_service.rb, app/services/sales_tax_service.rb, lib/address.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/lib/address_spec.rb, spec/services/gravity_service_spec.rb, spec/services/order_shipping_service_spec.rb, spec/services/sales_tax_service_spec.rb
It turns out TaxJar does not need a postal code for _seller nexus addresses_ -- the state is enough for sales tax calculation purposes. (We still need a postal code for shipping/artwork pickup addresses, though.) Additionally, our logic for validating addresses for sales tax calculations lives in the `Address` model when it should more properly live in `SalesTaxService`.
Refactor our address validation logic to reside in `SalesTaxService` and not require seller nexus addresses to have a postal code.
- Move sales tax address validation logic to `SalesTaxService`
- Separate out address validation based on role in sales tax calculation (i.e., destination address or seller nexus address)
- Create new `effective_shipping_total_cents` that stores the value of what amount we should use for …
=> Relax address validation requirements

app/graphql/types/query_type.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
We only want sales admins to access orders through our admin app.
Addresses [PURCHASE-627](https://artsyproduct.atlassian.net/browse/PURCHASE-627).
Remove ability for sales admins to access orders via GraphQL.
- Sales admins can no longer access orders via GraphQL
=> Remove ability for sales admins to access orders via GraphQL

app/controllers/errors/error_types.rb, app/services/order_service.rb, spec/controllers/api/requests/set_payment_mutation_request_spec.rb, spec/services/order_service_spec.rb
When setting the buyer's credit card on an order, we don't currently check whether or not the credit card is actually associated with the buyer's user. This creates a vulnerability where an attacker could pass in any credit card ID they choose.
Resolves [PURCHASE-583](https://artsyproduct.atlassian.net/browse/PURCHASE-583).
Verify that the user ID on the credit card ID given in `OrderService.set_payment!`  matches the buyer's user ID on the order.
=> Verify that credit given in set payment step belongs to buyer

_schema.graphql, app/graphql/types/order_type.rb, app/models/offer.rb, spec/controllers/api/requests/initial_offer_mutation_request_spec.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/models/offer_spec.rb
We want to filter out pending offers when returning `order.offers` in GraphQL by default and we want to allow option to adding them if needed.
https://artsyproduct.atlassian.net/browse/PURCHASE-649
Added a new scope for `submitted` offers to `Offer` model.
Updated `order.offers` to by default use `submitted` scope, and in case newly optional `includePending` was passed, add them to the response.
=> Filter out pending offers in order.offers

app/services/sales_tax_service.rb, spec/services/sales_tax_service_spec.rb
Partially reverts https://github.com/artsy/exchange/pull/239
Per legal's request, we're now going to be charging the _total_ collectable sales tax inclusive of state, city, county and other special jurisdiction taxes when calculating sales tax. Previously, we were only charging state sales tax.
Pass along whatever total tax amount we obtain in TaxJar's `amount_to_collect` parameter
- Stop using breakdown object in sales tax parameter to selectively pull out state sales tax and instead use `amount_to_collect` parameter.
=> Use total sales tax amount when calculating sales tax

_schema.graphql, app/graphql/types/order_interface.rb, spec/controllers/api/requests/deprecated_fields_requests_sepc.rb
This field is not used in Reaction anymore, in MP we [already switched it to use `itemsTotalCents` ](https://github.com/artsy/metaphysics/blob/master/src/schema/ecommerce/types/order.ts#L75), we are now good to remove it from Exchange.
=> Remove _deprecated_ offerTotal

spec/spec_helper.rb
This commit means that coveralls is only run on CI and no other
environment.
* Circle CI [sets the CI ENV variable][0]
* Cleans up stdout when running `rspec`
+ also, loading less code is almost always a good thing!
[0]:https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
=> Only run coveralls when on CI

Procfile.dev, README.md, bin/setup
Sarah and I were QA'ing an event sent from a not-yet-deployed version of
exchange to pulse. At some point, we realized that an event wasn't sent
to RabbitMQ because my local sidekiq wasn't running.
* Add a Procfile.dev to make it easier to remember the
system-level dependencies needed to this service.
* Document usage of Procfile.dev in README
* Add `gem install foreman` to bin/setup
=> Add Procfile.dev to ease local development

_schema.graphql, app/graphql/types/offer_order_type.rb, app/graphql/types/offer_type.rb, app/graphql/types/order_participant_enum.rb, app/models/offer.rb, app/models/order.rb, spec/controllers/api/requests/order_my_offer_request_spec.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/models/offer_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-664
We want to be able to show if an offer is from `Buyer` or `Seller`.
We already had a logic to detect this so we can return `awaiting_response_from` on `OrderType`. We added `from_participant` helper to `Offer`, we updated `awaiting_response_from` to also use this newly added method and exposed the new field in `OfferType`.
- Added `from_participant` to `Offer`.
=> Add from_participant to Offer and expose it in OfferType

_schema.graphql, app/graphql/types/offer_type.rb, spec/controllers/api/requests/add_initial_offer_to_order_mutation_request_spec.rb, spec/controllers/api/requests/offer_set_shipping_mutation_request_spec.rb
Exposes `buyerTotalCents` field on `OfferType` that returns the total amount the buyer is expected to pay for the offer.
Addresses [PURCHASE-684](https://artsyproduct.atlassian.net/browse/PURCHASE-684).
=> Add `buyerTotalCents` to `OfferType`

spec/rails_helper.rb
Before this change:
```
dl@phoenix:~/src/exchange * (notify-when-offer-is-approved)
$ rspec spec/system/visiting_order_details_spec.rb
Randomized with seed 50253
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:60646
.
```
After this change:
```
dl@phoenix:~/src/exchange * (notify-when-offer-is-approved)
$ rspec spec/system/visiting_order_details_spec.rb
Randomized with seed 10582
.
```
References:
- https://github.com/rspec/rspec-rails/issues/1897#issuecomment-352923675
=> Suppress puma loading message in system spec

app/jobs/post_order_notification_job.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-700
Now that the [commit][0] that refactored name of the job is on staging
and production and there are no scheduled jobs in Sidekiq with the name
PostNotificationJob, we are clear to remove this old alias.
[0]:aa470960628e0cc46636b3f947cd2c9f3152fe06
=> Remove reference to old PostNotificationJob

app/models/fulfillment.rb, app/models/line_item.rb, app/models/offer.rb, app/models/transaction.rb
Add `has_papertrail` to few other models, they will be less useful since these models don't technically get updated and are mostly created but still good to have them.
=> Add Papertrail to few other models

db/migrate/20181203203227_cleanup_old_versions.rb, db/schema.rb
This is follow up work on https://github.com/artsy/exchange/pull/299 to delete older invalid records and then update the column to be `uuid`.
This happens in a migration script where we:
- Delete older records not matching `uuid` format. This happens in the migration where we delete all records that don't match Postgres's uuid format.
- Change the `item_id` column to be `uuid`, for this to work we need to change column with 'uuid USING CAST(item_id AS uuid)'
we delete them from here, you can find old versions in RDS snapshot with name `exchange-before-deleting-old-papertrail-versions`
=> Papertrail Versions Followup

app/controllers/errors/error_types.rb, app/graphql/mutations/offer/base_accept_offer.rb, app/graphql/mutations/seller_reject_offer.rb, app/models/order.rb, app/services/commit_order_service.rb, app/services/offers/accept_offer_service.rb, app/services/offers/offer_validation_service.rb, app/services/offers/reject_offer_service.rb, app/services/offers/submit_order_service.rb, app/services/order_approve_service.rb, app/services/order_submit_service.rb, app/services/payment_service.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/services/commit_order_service_spec.rb, spec/services/offers/accept_offer_service_spec.rb, spec/services/order_submit_service_spec.rb, spec/services/payment_service_spec.rb
Addresses [PURCHASE-668](https://artsyproduct.atlassian.net/browse/PURCHASE-668).
This PR is for early feedback on creating our accept offer service layer.
**Tests will be reorganized / added / fixed in future commits.**
- Submitting an order and accepting an offer are fairly similar to each other -- in both cases, we need to deduct inventory, charge the buyer and update the state of the order. So, I've created a new class `CommitOrderService` that represents this sequence of events. Child classes can specify the next state of the order and implement their own payment method. I chose the name "commit" because once the inventory is deducted nobody else can claim that artwork unless the order is rejected or refunded. I'm definitely open to other names, though!
- Right now `PaymentService` …
=> AcceptOfferService deducts inventory and charges the buyer

app/services/tax/calculator_service.rb, spec/services/tax/calculator_service_sepc.rb
Per legal's request, this includes the cost of shipping in all sales tax calculations. Resolves [PURCHASE-713](https://artsyproduct.atlassian.net/browse/PURCHASE-713).
=> Include shipping cost in all sales tax calculations

hokusai/config.yml
This should ensure that running a `hokusai pipeline promote` pushes Git
tags even if not specified in as a command line argument. See [hokusai
docs][0] for more information.
[0]:
https://github.com/artsy/hokusai/blob/master/docs/Configuration_Options.md#project-configuration
=> Specify artsy/exchange as the `git-remote` for Hokusai

app/services/order_cancellation_service.rb, spec/services/order_cancellation_service_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-712
We are getting errors when trying to expiring (abandoning) offer orders.
In regular `OrderFollowUpJob` we call order cancelation's service's `seller_lapse` method which as part of it will try to refund the order by calling Stripe to release the hold charge and also tries to call Gravity to undeduct the inventory BUT for offer orders we don't have to call Stripe since we are not holding any charges yet and also we don't have to call Gravity since we haven't deducted the inventory yet. 
For offers, capturing the charge and deducting artwork inventory only happens when offer is accepted.
Skip `process_refund` when `order.mode` is `offer`.
=> Make sure we don't call refund and un-deduct on Offer Orders

app/graphql/mutations/offer/seller_counter_offer.rb, app/services/offers/add_pending_counter_offer_service.rb, spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb, spec/services/offers/add_pending_counter_offer_service_spec.rb
and `sellerCounterOffer` mutation
Realized `from_id` of an offer, when submitted from the seller side is the `partner_id` not` user_id`.
In case of a buyer offer they are the same though.
=> Add `creator_id` to AddPendingOfferService 

app/events/order_event.rb, spec/events/order_event_spec.rb
We want to know who made `last_offer` in case of offers and also details about it when sending out emails from Pulse.
Add `last_offer` to `order_event`'s `properties`.
=> Add last_offer to order event

_schema.graphql, app/graphql/types/line_item_type.rb
Once this is exposed, then I can update MP's schema and use it over there in the artwork version resolver.
=> Expose the artwork version id

app/controllers/errors/error_types.rb, app/graphql/mutations/offers/seller_counter_offer.rb, app/models/offer.rb, spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb, spec/models/offer_spec.rb
This PR addresses two issues:
1. In the seller counter offer mutation, `Order::PARTNER` is currently passed in as the `from_type` for every new pending offer created by `AddPendingCounterOfferService`. We should be using `order.seller_type` instead since the `seller_type` might not be "partner."
2. `Offer.from_participant` can currently return `nil` if, say, the offer `from_type` does not match the buyer or seller type. Since our UI depends on having this value not be null in some places (e.g., we use `Order.awaiting_response_from` in Reaction, which is defined by `Offer.from_participant`), this should  raise an error if we can't figure out the `from_type`.
=> Fix seller counter offer mutation bug and raise error on unknown offer participant type

app/events/order_event.rb, spec/events/order_event_spec.rb
To be used in Buyer Counteroffer email sent to seller:
=> Add responds_to hash to OrderEvent

lib/address.rb, spec/lib/address_spec.rb
State names must exactly match their corresponding name in Carmen in order to successfully be parsed into their abbreviation. A seller had a trailing space in their state name, which initially prevented an order from going through because we couldn't parse the state.
Addresses [PURCHASE-714](https://artsyproduct.atlassian.net/browse/PURCHASE-714).
Trim leading and trailing whitespace when parsing the region in `Address`.
=> Trim leading and trailing whitespace when parsing region

app/services/commit_order_service.rb, app/services/order_submit_service.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb
Addresses [PURCHASE-757](https://artsyproduct.atlassian.net/browse/PURCHASE-757).
Allows artwork mismatches when accepting an offer.
=> Do not raise error if artwork versions mismatch on accepting offer

.circleci/config.yml, hokusai/deploy_event.sh
Relies on DD_API_KEY being set in circle which I've already set up.
I know @izakp mentioned doing this in hokusai deploy hooks but to do that we'd need some mechanism where we could know in the hook if we're deploying to staging or prod. That would probably be nice so I'm still open to that path but this is simple and should be a good way to get started.
Events look like this and can be overlaid on metric graphs.
=> add datadog events on deploy

.rubocop.yml, app/services/offer_service.rb, spec/services/offer_service_spec.rb
After refactors in #336 where we consolidated the logic of what happens during offer submission to new style, we introduced a pretty complicated bug where after submitting an offer, we calculate tax based on the previous offer which then causes rest of the totals being calculated wrong.
https://artsyproduct.atlassian.net/browse/SELL-1262
When consolidating the logic for submitting offer, we ended up having setting `last_offer` on an order in one update with setting other totals.
when calculating totals for an order, we use `order.items_total_cents` which is calculated by the sum of all line item's `total_amount_cents`. In case of `Offer` orders, line item's `total_amount_cents` based on `order.last_offer` and with our current logic, at the time we try to get `items_total_cents`, …
=> Quick version of the fix for wrong tax calculation

app/events/offer_event.rb, app/jobs/post_offer_notification_job.rb, app/services/offer_service.rb, spec/events/offer_event_spec.rb
When an offer is submitted currently we are posting an `Order::SUBMITTED` event. There are 2 issues with it:
1) Order was not actually submitted :) Order was _submitted_ before and at this stage we are only adding a new offer but submitting a _pending_ Offer. 
2) Currently ☝️ event is used for sending emails when offer is submitted and they rely on order event's `last_offer` to send email for last email. The issue is, we queue jobs for posting these events, and technically speaking its possible that the `last_offer` may not be the offer we wanted to send event for at the time we are processing the job. In this case consumers will receive an event but there is no way for them to find the offer triggered this event originally.
Because of ☝️ reasons, we want to send an offer-based event when …
=> Add OfferEvent and post when offer is submitted

app/controllers/errors/error_types.rb, app/services/offer_service.rb, lib/order_data.rb, spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/submit_pending_offer_request_spec.rb, spec/services/offer_service_spec.rb, spec/support/gravity_helper.rb
We want to raise error when buyer/seller submit counter offers.
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-767
In submission logic, check if we have enough inventory for this order's artwork.
Processing error with `insufficient_inventory` as error code.
=> Check inventory before offer submit

app/events/offer_event.rb, spec/events/offer_event_spec.rb
follow up on #350 which was already a follow up itself.. this PR adds full `in_response_to` to the event which is used by some consumers instead of just having the id.
=> Follow up on followup to add full in_response_to

app/services/offer_service.rb, spec/services/offer_service_spec.rb
This PR removes posting `order.submitted` for offer submission. We now only send `offer.submitted` events.
=> Stop posting order.submitted for offer submission

app/graphql/mutations/submit_order_with_offer.rb, app/services/offer_service.rb, spec/services/offer_service_spec.rb
When offer orders are submitted we don't get emails or slack notification.
As part of https://github.com/artsy/exchange/pull/338 I missed posting order events for submitting order with offer.
Add it back and add tests for it.
=> Missed posting orderNotification after refactor

lib/order_creator.rb, spec/controllers/api/requests/offers/create_offer_order_with_artwork_mutation_request_spec.rb, spec/lib/order_creator_spec.rb, spec/services/order_service_spec.rb
When a user has a `buy` order, when they try to make offer we return their `buy` order. 
https://artsyproduct.atlassian.net/browse/PURCHASE-778
When checking for existing orders, we were not checking `mode`.
Check for `mode` when looking for `existing_order `
=> Reuse orders only if it's same mode

app/events/offer_event.rb, app/events/order_event.rb, spec/events/offer_event_spec.rb, spec/events/order_event_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-777
Subject id is currently not included in event `properties` because we have that in `subject` separately. However, when nesting event properties in another event (e.g. [`order`](https://github.com/artsy/exchange/blob/4e33c444b27e750e6d30563112b8c32bada58bbe/app/events/offer_event.rb#L38) nested in an offer event), the consumer would [not get the id of the nested object](https://github.com/artsy/pulse/blob/0150d792a02cd74d52b404463c99e02067d8527a/app/event_handlers/seller_countered_offer_handler.rb#L27).
Let's always include id in the event properties. It's a bit of redundancy, but the id field seems essential to me.
=> PURCHASE-777: Include subject id in event properties

.rubocop.yml, app/models/order.rb, app/services/offer_service.rb, app/services/order_approve_service.rb, app/services/order_submit_service.rb
We want to switch Pulse emails to use Exchange notification instead of queuing their own job in the future for reminder emails. https://github.com/artsy/pulse/pull/325
Currently reminder notifications are posted only 2hrs before expiration and only consumer is APRb for these for slack notification. Emails need to be sent 5hrs before expiration. After talking to CRT we are good with getting internal notifications at 5hr too.
We updated reminder notification to 5hrs and this way pulse could switch to these events.
For existing ones we still use 2hrs since they were already queued, if we want to not send emails 2hrs before for existing jobs we can follow this:
- Deploy Exchange with this change
- Wait 2 days (so all jobs queued in 2 days from the deploy time are finished)
- Merge …
=> Update reminder emails to 5hrs before expiration

app/jobs/undeduct_line_item_inventory_job.rb, lib/gravity.rb
[Discussed in Slack](https://artsy.slack.com/archives/CB110C6LE/p1546616701076600?thread_ts=1546616137.073300&cid=CB110C6LE), this PR is a follow-up to #364 and [PURCHASE-718](https://artsyproduct.atlassian.net/browse/PURCHASE-718). This PR changes calls to gravity's `inventory` endpoint to undeduct inventory (typically from a refund). If the API call fails due to a 404 (a deleted artwork) then it won't be retried. I looked for other places we call this undeduction, and I don't see any issues with not retrying.
=> Ignores deleted artworks during inventory undeduction

lib/shipping_helper.rb, spec/lib/shipping_helper_spec.rb
In rare instances it's possible to end up attempting to calculate shipping with a missing artwork location.
Addresses [PURCHASE-786](https://artsyproduct.atlassian.net/browse/PURCHASE-786).
Raise a `missing_artwork_location` error if the artwork location is blank when we try to calculate shipping costs.
- `ShippingHelper#calculate` raises an error if artwork location is blank when trying to calculate shipping costs
- Refactored domestic shipping logic in `calculate` into its own method `domestic?`
=> Raise error if missing artwork location in ShippingHelper.calculate

app/admin/orders.rb
- Removes "buyer total" column
- Removes "last admin action" column
- On right side filters, changes “mode” to say “type”
- ( https://artsyproduct.atlassian.net/browse/SELL-1281 )
=> SELL-1281 - Updates admin GUI

app/admin/orders.rb
When artwork is missing square image we are not able to render the admin page.
https://exchange.artsy.net/admin/orders/266559b8-88d5-4a4c-acbd-ba6dd18b3e84
Add some defensive code.
=> Fix missing square image

_schema.graphql, app/graphql/types/order_interface.rb
~WIP because this PR depends on [a metaphysics PR](https://github.com/artsy/metaphysics/pull/1471) being merged **and deployed**.~ The metaphysics PR has been merged, so this one's ready to go!
*Partially* resolves https://artsyproduct.atlassian.net/browse/PURCHASE-796. We will still want to update all metaphysics clients that keep versions of the schema.
=> Remove deprecated “lastOffer” and “offers” fields from “Order” interface

app/models/order.rb
In ActiveRecord, almost all `#pluck` calls could be replaced with `#select`. This will consolidate the three SQL queries sent individually and reduce extra network roundtrip and memory footprint.
```sql
SELECT "line_items"."artwork_id" FROM "line_items" WHERE "line_items"."order_id" = $1  [["order_id", "..."]]
SELECT "line_items"."edition_set_id" FROM "line_items" WHERE "line_items"."order_id" = $1  [["order_id", "..."]]
SELECT *
FROM "orders"
INNER JOIN "line_items" ON "line_items"."order_id" = "orders"."id"
WHERE orders.id != '...'
AND orders.state = 'submitted'
AND (
line_items.artwork_id IN ("...", "...") OR
line_items.edition_set_id IN ("...", "...")
)
```
```sql
SELECT *
FROM "orders" 
INNER JOIN "line_items" ON "line_items"."order_id" = "orders"."id" 
WHERE orders.id != '...'
AND …
```
=> Use SQL subqueries to reduce extra network roundtrips

db/migrate/20190128180430_switch_to_bigger_int.rb, db/schema.rb
We are using `int` for all of our amount fields, that limits us to max of 2,147,483,647 cents or $21,474,836.47 
We want to use `bigint` just in case that day comes....
https://artsyproduct.atlassian.net/browse/PURCHASE-771
Add an irreversible migration for switching all amount fields in different models to bigint.
=> Switch to bigint for all cents fields

app/events/offer_event.rb, spec/events/offer_event_spec.rb
This includes the offer note in the event that we send to rabbit.
The length of the note is constrained client-side, so we're not likely to get ones > 200 characters.
=> Adds note to offer event

Gemfile.lock, app/events/offer_event.rb, app/events/order_event.rb, app/jobs/post_event_job.rb, app/services/offer_service.rb, app/services/order_approve_service.rb, app/services/order_cancellation_service.rb, app/services/order_service.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/confirm_pickup_request_spec.rb, spec/controllers/api/requests/offers/reject_offer_mutation_request_spec.rb, spec/services/offer_service_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/services/order_service_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-761
We queue jobs for posting order and offer events. Depending on whats the current state of the order/offer some fields may be wrong if by the time Sidekiq is processing the job, the order/offer is already updated.
Add `delay_post` to both `OrderEvent` and `OfferEvent` which create the event and queue a newly added `PostEventJob` which gets an event json string and also the routing key.
We can remove `PostOrderNotifictionJob` and `PostOfferNotificationJob` since we've moved to `PostEventJob`.
=> Use order/offer snapshot before queuing the event job

app/events/offer_event.rb, app/events/order_event.rb, app/jobs/post_event_job.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/confirm_pickup_request_spec.rb, spec/events/order_event_spec.rb, spec/jobs/post_event_job_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/services/order_service_spec.rb
Follow up on #347 where we missed passing `topic` to the method and it was using not existing `TOPIC`.
Also added a missing spec and added `note` to `OrderEvent`'s `last_offer` in `properties`
=> Fix missing Topic in post_event

app/services/offer_service.rb, app/services/order_service.rb, spec/services/order_approve_service_spec.rb
#347 got merged, we had some other changes already in Exchange for switching to new style for submit order events. The merge caused issue in posting two events in case of Order submission.
This removes the duplicate and also remove last usages of `PostOrderNotificaiton` and switches to `OrderEvent`.
=> Fix merge issue with posting two events

app/controllers/errors/failed_transaction_error.rb, app/services/offer_service.rb, app/services/order_service.rb, lib/order_processor.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/lib/order_processor_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-872
When we call Stripe to process a charge (hold/capture) regardless of the success or failure, we want to store the response as  a `Transaction`. For failed transactions we also post event so we can get notified about them on Slack.
We were notified about a failed charge yesterday and noticed we haven't received slack notifications for them. Looking deeper at the issue, we noticed this failed transaction was not stored on the order.
This bug was introduced as part of #379 . What happens here is, we had test in newly added `OrderProccessor` to check if we create a failed transaction in the order in case of Stripe charge failures BUT `order_proccessor.charge` and `order_proceessor.hold` where called in one of `order.<action>` blocks which …
=> Fix Missing Failed Transaction

app/controllers/errors/error_types.rb, app/models/order.rb, app/services/order_approve_service.rb, app/services/order_cancellation_service.rb, app/services/order_service.rb, db/migrate/20190311132730_add_payment_method_to_orders.rb, db/schema.rb, lib/order_creator.rb, lib/order_processor.rb, spec/fabricators/order_fabricator.rb, spec/lib/order_processor_spec.rb, spec/models/order_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/services/order_service_spec.rb
We need to be able to represent orders that are paid for by methods other than `credit_card`, even if we don't have _full_ support for those payment methods just yet.
This PR adds a `payment_method` field to the `Order` model and raises errors in places where we'd attempt to charge a cc for an order that had this set.
From an admin-perspective, if we have a UI for creating orders with `wire_transfer`, they'll have to be in the "approved" or "fulfilled" state, since we don't want to unknowingly mess with inventory or availability just yet. It gets complex 😅
=> Add payment method (include support for wire transfer)

app/events/transaction_event.rb, app/models/transaction.rb, db/migrate/20190319164840_add_decline_code_to_transactions.rb, db/schema.rb, lib/payment_service.rb, spec/lib/order_processor_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/payment_service_spec.rb
When a charge fails, we’re not currently capturing the decline_code from Stripe. We need this data so we can distinguish between a charge failing due to insufficient_funds vs. other failures, like do_not_honor.
See https://stripe.com/docs/declines/codes for examples.
We’ll want to store this information on a Transaction in exchange, and expose it through the mutation payload and in TransactionEvent.
=> Exchange stores and returns the decline_code when a charge/hold/etc. fails

app/controllers/errors/application_error.rb, app/controllers/errors/processing_error.rb, app/controllers/errors/validation_error.rb, app/events/application_error_event.rb, lib/line_item_totals.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/controllers/errors/application_error_spec.rb, spec/events/applicaiton_error_event_spec.rb
We want to get notified on slack when some special errors happened in Exchange. Mainly things that are actionable like when partner address is invalid.
Add new `ApplicationErrorEvent` and add optional `post_event` param to exception initialize which by default is `false`. When it's set to true we post a newly added `ApplicaitonErrorEvent`.
This new event follows are existing pattern of `object`, `subject`, `verb` and `properties` but `subject` is always `nil`.
Currently we only request to post this event on address verification errors, but talked to @sweir27 about opening it up to all validation errors.
=> Post events when requested on ApplicationError

lib/line_item_totals.rb, lib/offer_totals.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
When we did #400 , we missed posting similar events during offer submission.
This PR adds the missing part from ☝️ also fixed wrong `line_item` id posted in data.
=> Follow up on error events

app/admin/orders.rb, app/jobs/record_sales_tax_job.rb, lib/gravity.rb, lib/order_helper.rb, spec/controllers/api/requests/offers/buyer_counter_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/lib/gravity_spec.rb, spec/lib/order_shipping_spec.rb
e.g. 'Business' and 'Sales tax nexus'
**#do_not_merge:** we need to validate partner addresses before merging this
Depends on https://github.com/artsy/gravity/pull/12274
Fixes [GALL-1453](https://artsyproduct.atlassian.net/browse/GALL-1453)
=> #coordinate-deploy Only pass valid addresses to taxjar #DONOTMERGE

app/admin/orders.rb, db/migrate/20190530201701_add_clc_assisted_to_order.rb, db/schema.rb
When CRT assists a buyer during checkout, they often mention in slack that this order was created with CLC's help. 
This information seems to be important to them but currently lost in Slack.
https://artsyproduct.atlassian.net/browse/PURCHASE-1147
Add a `clc_assisted` flag to `Order` and allow to toggle it from the admin UI.
=> #FF Add clc_assisted to Orders and to admin

lib/payment_service.rb, spec/services/payment_service_spec.rb
During adding #412 noticed that for successful capture transactions, we store the whole `source` coming back from Stripe in `source_id` field of `Transaction`. 
```ruby
Transaction.where(transaction_type: Transaction::CAPTURE).first.source_id
=> "{\n  \"id\": \"card_1DjZ47GK3Gnpfa3O5rULDzXE\",\n  \"object\": \"card\",\n  \"address_city\": \"Minneapolis\",\n  \"address_country\": \"US\",\n  \"address_line1\": \"3017 Harriet Ave\",\n  \"address_line1_check\": \"pass\",\n  \"address_line2\": \"\",\n  \"address_state\": \"MN\",\n  \"address_zip\": \"55408\",\n  \"address_zip_check\": \"pass\",\n  \"brand\": \"Visa\",\n  \"country\": \"US\",\n  \"customer\": \"cus_E5V2tn9XLAna9Z\",\n  \"cvc_check\": \"pass\",\n  \"dynamic_last4\": null,\n  \"exp_month\": 4,\n  \"exp_year\": 2024,\n …
```
=> PURCHASE-1137: Fix storing source instead of source.id in transaction.source_id

spec/integration/single_counteroffer_happy_path_spec.rb, spec/support/offer_query_helper.rb
This PR adds a spec for the "happy path" scenario in which:
1. Buyer creates initial offer (and adds shipping, payment, etc.)
2. Seller counters that offer
3. Buyer accepts that offer
Since the first step here (buyer creating the offer) is validated in the "make offer happy path" spec, I had it go through the actions but I didn't repeat the assertions. Happy to revisit if you think I'm losing value here!
=> PURCHASE-1138: Adds spec for the single counteroffer happy path scenario

app/models/order.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/events/offer_event_spec.rb, spec/events/order_event_spec.rb
We need to extend approval expiration to 72 hours.
fixes https://artsyproduct.atlassian.net/browse/PURCHASE-1180
No, once deployed to prod, it will impact *only* orders submitted after the deployment, for those order, approval expiration will be 3 days.
I thought about it, but I think this is somehow significant enough change that might still be better to go  through PR and code review. For example extending this beyond 7 days will have charge expiration issue. 
Pulse and Force have been already updated to show expiration based on `stateExpiresAt` and not hardcode in:
https://github.com/artsy/reaction/pull/2571
https://github.com/artsy/pulse/pull/372
=> [PURCHASE-1180] Extend approval expiration to 3 days

app/models/offer.rb, spec/controllers/api/requests/offers/submit_order_with_offer_mutation_request_spec.rb
When we tested #430 on staging, looks like buy now orders get proper expiration but for MO we still get 2 days.
We had a separate const for offer expiration, this probably originally was designed this way so we can decouple offer and order expirations since offers are less timely. For example, its ok to set expiration on an offer to be 8 days but we can't do that on order since stripe hold will expire.
Update offer expiration to 3 days.
=> Update offer expiration to match submitted order expiration

.circleci/config.yml
following up on https://github.com/artsy/vibrations/pull/452 and https://artsy.slack.com/archives/CA8SANW3W/p1563195752298200
=> Remove unused image push during prod deploy

.rubocop_todo.yml, Gemfile, Gemfile.lock, _schema.graphql, app/controllers/errors/error_types.rb, app/controllers/errors/payment_requires_action_error.rb, app/graphql/mutations/order_or_failure_union_type.rb, app/graphql/mutations/submit_order.rb, app/models/transaction.rb, app/services/order_service.rb, db/migrate/20190717161109_add_external_type_and_payload_to_transactions.rb, db/migrate/20190717171856_populate_transaction_external_type.rb, db/schema.rb, lib/order_processor.rb, lib/payment_service.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/integration/buy_now_happy_path_spec.rb, spec/integration/make_offer_happy_path_spec.rb, spec/integration/single_counteroffer_happy_path_spec.rb, spec/lib/order_processor_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/services/payment_service_spec.rb
This adds `external_type` to `transactions` table, this way we can distinguish between `charge`, `refund` and newly added `payment_intent` transactions.
This way when trying to `capture` or `refund` we first find the `transaction` for this `external_id` and based on it's type decide if we need to do a `charge` or `payment_intent` refund/capture.
=> Transaction external type

app/models/order.rb, spec/integration/gbp/buy_now_happy_path_spec.rb, spec/integration/gbp/make_offer_happy_path_spec.rb, spec/integration/gbp/reset_shipping_request_spec.rb, spec/integration/gbp/single_counteroffer_happy_path_spec.rb, spec/models/order_spec.rb, spec/support/use_stripe_mock_gbp.rb
This PR adds GBP to the list of supported currencies in Exchange. The list of supported currencies is used to validate the currency of a new order, and without GBP, collectors will not be able to click on the "Buy now" or "Make offer" buttons on Artsy.net to begin the order or offer flow.
- In order for artworks enrolled in NSO to be listed in GBP, partners need to have access to the `CMS UK Commerce` lab feature, so this change does not pose a risk to existing NSO artworks in production.
- This PR adds "happy path" integration tests for GBP artworks to ensure that orders can be created from GBP artworks and retain the same currency through the order and offer flows. These tests do not, however, use UK addresses for the seller and buyer since more work will be needed to [correctly …
=> Make GBP a Supported Currency for Orders (GALL-1966)

.rubocop.yml, app/controllers/errors/insufficient_inventory_error.rb, app/events/transaction_event.rb, app/jobs/post_transaction_notification_job.rb, app/services/offer_service.rb, app/services/order_service.rb, lib/gravity.rb, lib/order_processor.rb, spec/controllers/api/requests/line_items_query_request_spec.rb, spec/events/transaction_event_spec.rb, spec/jobs/post_transaction_notification_job_spec.rb, spec/lib/order_processor_spec.rb
When we started updating our logic around adding support for `PaymentIntents` which would add more conditions to a _failed payment_. Things got pretty complicated between `OrderProcessor` and how it's being used by `OrderService` and `OfferService`.
One thing that complicated things was who and where we raise exceptions and how and where we rescue from them. We were relying on exception raised from `OrderProcessor` to _rollback_ the status changes during order/offer `submit`.
instead of raising exceptions from `OrderProcessor`, have it set the status internally so the callers can decide what to do with the failed reason. 
This will help us later when we try to handle `requires_action` case of `PaymentIntent` but we should look at this PR regardless of the coming changes.
=> Refactor order_processor to not raise error

app/controllers/errors/error_types.rb, app/models/transaction.rb, app/services/order_approve_service.rb, app/services/order_cancellation_service.rb, config/initializers/stripe.rb, db/migrate/20190723204933_add_external_type_and_payload_to_transactions.rb, db/migrate/20190723204947_populate_transaction_external_type.rb, db/schema.rb, lib/order_processor.rb, lib/payment_service.rb, spec/controllers/api/requests/approve_order_mutation_request_spec.rb, spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb, spec/controllers/api/requests/line_items_query_request_spec.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/buyer_counter_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/reject_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/integration/buy_now_happy_path_spec.rb, spec/integration/make_offer_happy_path_spec.rb, spec/integration/single_counteroffer_happy_path_spec.rb, spec/lib/order_processor_spec.rb, spec/services/order_approve_service_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/services/payment_service_spec.rb, spec/support/stripe_helper.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1331
As part of our path to support for SCA, we need to switch to Stripe's [`PaymentIntent` API](https://stripe.com/docs/payments/payment-intents). 
This means we need to move way from directly using `Charge` API. We need to create a `PaymentIntent` at the time we are trying hold or capture a charge and confirm it. 
* A successfully confirmed `PaymentIntent` will lead to a charge.
* PaymentIntents can fail for different reason when we confirm:
- They can fail confirmation: Payment intent goes to `require_action` state (not supported in this PR) meaning we need to ask buyer to go through SCA.
- They can fail processing charge: (think of insufficient funds and etc.) Payment intent goes to `require_payment_method` state (maps to our current …
=> Switch to payment intent stuff

.rubocop.yml, lib/payment_service.rb, spec/services/order_approve_service_spec.rb, spec/services/payment_service_spec.rb, spec/support/stripe_helper.rb
Looking at Stripe's docs about PaymentIntent, looks like [they always return](https://stripe.com/docs/api/payment_intents/create) a payment object when creating a new one. So we thought if a payment intent fails because of card errors (insufficient funds and etc.) we would get a payment intent back with`requires_payment_method` status.
Turns out thats not the case after we actually tried it on staging. After talking to Stripe engineers, looks like in two cases we'd get exceptions and we'd need to rescue:
- Anytime card gets declined
> we will throw an error on any decline
- In an `off_session` payment intent, Stripe will _decline_ if card `requires_action`:
> The tricky thing here is that Stripe will decline if a PaymentIntent is off_session and the PaymentMethod requires authentication. …
=> Fix Failed Payment Intent Issue

db/migrate/20190723204947_populate_transaction_external_type.rb
Update data migration that was missing `%` when doing a prefix matching for `external_id`.
=> Fix data migration to actually use prefix

app/services/offer_service.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/integration/make_offer_happy_path_spec.rb
When we tried to refund our test offer orders on production we noticed the refund fails.
During [our refactor](https://github.com/artsy/exchange/pull/442) we moved the responsibility of setting `external_charge_id` on an `Order` from `order_processor` to the caller. We fixed `order_service` to set it in a successful transaction but we missed it on the `offer_service`.
Any offers approved after deploy https://github.com/artsy/exchange/pull/444 won't have `external_charge_id` so can't be refunded. 
NOTE BN orders are fine and also partner's don't have the option for refund, this all happens by our admins from exchange admin.
Update `offer_service` to set `external_charge_id` in case of success and add tests for it.  
for offers approved in last 4 days without `external_charge_id` we have to …
=> Fix missing setting external_charge_id on approved offers

_schema.graphql, app/graphql/types/fulfillment_type.rb, app/graphql/types/line_item_type.rb, app/graphql/types/offer_type.rb, app/graphql/types/order_interface.rb, spec/controllers/api/requests/order_query_request_spec.rb
Follows https://artsyproduct.atlassian.net/browse/PLATFORM-1448 to add `internalID` to all our types pointing to ID.
have our mutations/queries accept `internalID`
=> Add internalID to all our types

spec/models/order_spec.rb
Exchange `rspec` was showing warnings about checking for not raising an error.
```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /app/spec/models/order_spec.rb:10:in `block (3 levels) in <top (required)>'
``` 
instead of `update!` set the values for those attributes and check for …
=> Fix `rspec` warning

_schema.graphql, app/graphql/types/offer_type.rb, spec/integration/gbp/make_offer_happy_path_spec.rb, spec/support/offer_query_helper.rb
This adds `currency_code` as a field returned in an `Offer`'s graphQL response.
This will allow `amount` fields on `Offer` to be formatted correctly in metaphysics.
=> Expose currency_code in offer graphQL response

.rubocop.yml, _schema.graphql, app/controllers/errors/error_types.rb, app/controllers/errors/payment_requires_action_error.rb, app/graphql/mutations/order_or_failure_union_type.rb, app/graphql/mutations/submit_order.rb, app/graphql/types/order_action_data_type.rb, app/models/transaction.rb, app/services/order_service.rb, hokusai/sca.yml, lib/order_processor.rb, lib/payment_service.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/lib/order_processor_spec.rb, spec/services/payment_service_spec.rb, spec/support/stripe_helper.rb
during #443 we switched over to `PaymentIntent` instead of charge. But that change yet doesn't support new status we could get back from that API where PaymentIntent was not `succeeded` and needed `requires_action`.
In `requires_action` case, we store a transaction in `Transaction` with status being newly added `Transaction::REQUIRES_ACTION`.
We also update the order's `external_charge_id` to be this payment intent's id so we can reuse it later when user was done with 3d auth.
When a `PaymentIntent` goes to `requires_action` state, we need to return `client_secret` of the `payementIntent` back to the client, so client can use it to call Stripe.js to open popup and go through 3d auth process. The way we do this is by updating our existing `OrderOrFailureUnion` type to also now possibly …
=> Add support for `requires_action` payment_intent state

.rubocop.yml, .rubocop_todo.yml, app/services/order_service.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb
This is follow up on #455 where we missed rollback on case of `reuqires_action` payment intents.
Things get more complicated in `submit` method with this change, so im thinking of attempting the refactor after this PR but for now this should fix existing bug on `master` and staging.
=> Rollback when requires_action

.rubocop.yml, lib/order_processor.rb, lib/payment_service.rb, spec/services/payment_service_spec.rb
Send shipping address when creating payment intents.
part of https://artsyproduct.atlassian.net/browse/PURCHASE-1377
Why not?!
well, giving stripe more info can help them (and ultimately us) to do better job detecting fraud.
=> Send shipping address to stripe

app/controllers/errors/error_types.rb, app/models/transaction.rb, lib/order_processor.rb, lib/payment_service.rb, spec/integration/buy_now_sca_path.rb, spec/services/payment_service_spec.rb, spec/support/stripe_helper.rb
In #455 we started supporting `requires_action` state of `PaymentIntent`. In this case, we notify clients about this state and provide them with `client_secret` for this specific PaymentIntent which will be used to call `stripe.js`'s method to open 3D auth process.
Once 3D auth was successful, we call Exchange to submit the order again. In this case, we don't want to create a new payment intent, we have to confirm the existing one assuming its in `processing` [state](https://stripe.com/docs/payments/intents#intent-statuses).
This PR checks to see if during submission, order has `external_charge_id` set, we will confirm that payment intent instead of creating a new one.
When we get to requires action case, it's possible that user instead of going through 3D auth, they decide to change …
=> Confirm payment intent

app/graphql/types/mutation_type.rb, app/services/order_service.rb, spec/controllers/api/requests/set_payment_mutation_request_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1369
Went with easier solution in which we basically clean `external_charge_id` on the order which would lead to create new payment intent when user tries to submit again with new payment method.
=> clear external_charge_id when updating payment_method

.rubocop.yml, app/models/transaction.rb, app/services/order_cancellation_service.rb, lib/payment_service.rb, spec/controllers/api/requests/reject_order_mutation_request_spec.rb, spec/services/order_cancellation_service_spec.rb, spec/support/offer_query_helper.rb, spec/support/stripe_helper.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1379
We learned the hard way that when a payment intent is not captured yet, we need to use `payment_intent.cancel` and if payment intent was captured, then we need to first find the charge associated with that payment intent and use refund API to refund it.
We were under impression that we can always refund the charge associated with payment intent knowing that a uncaptured payment intent will still have charge associated with it.
In case of `seller_lapse`, `seller_reject` and buyer reject (only for BN), we now call newly added `cancel_payment_intent` method instead of calling refund.
=> Cancel payment intent instead of refund when un-captured

lib/payment_service.rb
During #462 we attempted to pass shipping information to Stripe when available. With current code if order type is pickup, we send empty hash which seems to cause stripe raising 
```
Invalid Hash.
```
Its hard to test this since this happens from Stripe end and we dont have a proper Stripe mock server.
pass all keys but use safe call
=> Fix passing empty hash

app/events/transaction_event.rb, spec/events/transaction_event_spec.rb
We want to be able to fetch stripe details for a transaction when receiving a transaction event from consumer side. For that to work we need `external_id` and `external_type` of a transaction.
Add those to `TransactionEvent.properties`.
cc: @iskounen @starsirius @bhoggard
=> #FF Add external_id and type to transaction events

app/events/transaction_event.rb, spec/events/transaction_event_spec.rb
This PR updates the `TransactionEvent` event to include shipping information in the data that it publishes to a messaging queue when a transaction fails. This change allows CRT to have access to the shipping address' country and name fields when they are notified of a failed transaction, which will help them determine if there is a potential fraud case faster.
=> #FF Include Shipping Info in Transaction Event Payload

lib/tax/calculator_service.rb, spec/integration/gbp/buy_now_happy_path_spec.rb, spec/integration/gbp/make_offer_happy_path_spec.rb
The purpose of this PR is to update the tax calculation logic in Exchange to prevent sales tax being calculated for an order (or offer-order) if the buyer is purchasing an artwork located outside of the United States. This is being done so that orders for artwork located in the UK aren't taxed once we enable NSO for UK partners.
This diagram explains what happens after a buyer enters their shipping information during the Buy Now flow, with a focus on how sales tax is calculated. This PR adds the section highlighted in red.
=> Prevent Tax Calculation for Artworks Outside the United States (GALL-1942)

lib/order_processor.rb, spec/lib/order_processor_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1403
We've started using Stripe Radar rules, we want to be able to have different rules for `bn` and `mo` cases, at the moment we can't do that wit our metadata.
`type` is used by `fianance` to group `bn-mo` orders calculation together. Instead of separating them, we added a new `mode` metadata to capture the order mode.
As part of our QA we noticed if anything other than expected `Errors::InsufficientInventoryError` goes wrong we don't undeduct inventory. Not sure how many times this could have possibly happen in prodcution since the types of errors we've seen so far on staging are mostly because of our tests but adding this undeduct makes sense and def helps our tests.
=> Add new mode to charge metadata + undeduct in case of other errors

.rubocop.yml, app/services/order_service.rb
Not much honestly, just like to be able to know how often require action happens.
add statsd with `submit.requires_action`
=> Add statsd for require action

.rubocop.yml, app/models/order.rb, app/services/offer_service.rb, app/services/order_service.rb, lib/order_processor.rb, spec/lib/order_processor_spec.rb
As we started building on top of existing code around submitting an `Order`, things got more complicated. Looking deeper at our process and after few brainstorming, it seems the part that complicates things the most is us having most of business logic during submit in a `order.submit!` or `order.approve!` block. Anything in that block is using `order.with_lock` and is part of one database transaction.
While having everything during wrapped in one db transaction helps our data integrity, because of external dependencies like inventory deduction in Gravity and charge processing in Stripe, we can easily get into a rollback scenario. Rollback case also gets pretty complicated because in some cases we want to store transactions in some cases we don't.
Instead of wrapping everything in a …
=> Refactor order_processor to be less dependent to db transactions

app/services/offer_service.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/services/offer_service_spec.rb
current failed payment flow works when a seller accepts an offer and payment doesn't go through, we send email to buyer about the failed payment and they fix their issue.
we need to make sure this works also for the case were we confirmed setupintent and later when seller accepts offer we tried to process off-session payment intent but that fails
Currently, whenever an offer is directed to a seller, the PaymentIntent is always off-session. However, for our existing failed payment flow, the buyer is technically accepting their own offer, which will be to a seller. Because of this, the PaymentIntent created has `off-session: true` when its really on-session. 
I changed the logic in `accept_offer` so that a payment is off session when the offer is directed to the seller AND the `user_id` …
=> PURCHASE-1428: Get failed payment flow working with case where payment intent of a already confirmed setupintent fails when seller accepts offer

spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb
Order by created_at before calling .last
=> Fix for failing tests on master

_schema.graphql, app/graphql/mutations/submit_order_with_offer.rb, app/services/offer_service.rb, lib/offer_processor.rb, lib/payment_method_service.rb, spec/lib/offer_processor_spec.rb, spec/lib/payment_method_service_spec.rb, spec/services/offer_service_spec.rb, spec/support/stripe_helper.rb
Currently when a user submits a Make Offer order, we initiate a `SetupIntent` with Stripe, if buyer had to go through SCA, we open the pop up on front end. Once they successfully finish auth, we will resubmit the order.
Current treats resubmit the same way as original submission, it will create a new `SetupIntent` and try to confirm it, because user has already confirmed previous setup intent, this second one goes through without needing SCA BUT we are creating extra SetupIntents and possibly involving the bank.
Stripe suggested that instead, when we resubmit, pass along the Setup intent ID (which is available in `handleCardSetup` js callback) and on the server side if thats available, instead of creating a new intent, just verify the one passed in. …
=> Reuse Confirmed SteupIntent

app/models/order.rb, spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1453
Current failed payment flow checks to make sure `last_transaction_failed` if it was not _failed_ it would raise error and wont allow going through this flow. In case the last transaction was in `require_action` state which is the state out of SCA, on the front end it would redirect you to status page https://github.com/artsy/reaction/blob/152acf20c68fdb7ebcc367f798a03bb2fdf74305/src/Apps/Order/redirects.tsx#L123
Updated `last_transaction_failed?` to also consider `require_actions` cases and added tests around it.
=> Fix failed payment with required action

.rubocop.yml, app/graphql/mutations/fix_failed_payment.rb, app/services/offer_service.rb, lib/order_processor.rb, spec/integration/fix_failed_payment_flow_with_sca_card.rb, spec/lib/order_processor_spec.rb, spec/services/offer_service_spec.rb, spec/support/offer_query_helper.rb, spec/support/stripe_helper.rb
Current fix failed payment flow is currently broken when using a card that needs SCA.
When buyer uses a SCA card during failed payment flow, it currently creates a new payment intent instead of using the one that was just confirmed as part of SCA popup. 
Update `order_processor.charge` to do same thing as `hold` where we check if there is already `external_charge_id` on the `order`, instead of creating new payment intent, confirm the existing one.
This change above though brought up a new bug where we realized currently we set `external_charge_id` on the `order` if transaction didn't fail, so in case transaction `requires_action` we would set it on the `order` so we can reuse it later. BUT in case of `off-session` (seller accepting offer) we don't want to reuse that payment intent anymore …
=> Reuse payment intent on resubmitting during failed payment flow

lib/order_processor.rb, spec/integration/fix_failed_payment_flow_with_sca_card.rb, spec/lib/order_processor_spec.rb
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-1474
As part of [the famous "refactor"](https://github.com/artsy/exchange/pull/475), its possible for an order to go to some state and then go back to previous one of the attempt to create charge or deduct failed on the order.
This seems to have cause a new bug where we update the `state_expires_at` on the orders and extend them in failed payment flow. Meaning if the order's expiration was tomorrow, and seller tries to accept the offer, order goes to `approved` for a sec, charge fails, and order goes back to `submitted` state, but because of new transition to `submitted` expiration will now be 3 days from now instead of original 1 day.
In `OrderProcessor` before transitioning order state, keep track of current `state_expires_at` and …
=> PURCHASE-1474: Wrong expiration on offers with failed payment flow

app/admin/orders.rb
currently order admin page is broken for offers
We are trying to access `currency_code` on `offer` but thats set on `order`.
Switch to `offer.order.currency_code`.
cc: @oxaudo
=> Fix issue with offer page in admin

app/graphql/types/query_type.rb, lib/artsy_auth_token.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
In order to allow admins into the order pages in CMS, they have to be able to see the order data at the GQL layer. Without a change like this nothing would be returned to Volt for them to look at!
Note: I believe that what this PR does is allow admins access to query for orders, but does not allow them access to mutate them, but would love confirmation of this!
=> GALL-2120: Relax admin check

app/models/order.rb
We need this in case that transaction went offline and we are not sure if it was paid by wire or not.
=> Introduce new other payment method

app/graphql/types/query_type.rb, lib/artsy_auth_token.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
Hot on the heels of my other PR #498, I'm following up here with one that restricts order access to admins with either `partner_support` or `sales_admin` roles. While I was at it, I added tests for both of these.
=> Restrict order access to just trusted admin roles

app/graphql/types/query_type.rb, lib/artsy_auth_token.rb, spec/controllers/api/requests/order_query_request_spec.rb
The roles property is a string that is a comma separated list of roles. Need to split it up into an array in order to compare against trusted roles. I also updated a spec to more closely match how roles are passed in (as a string that's actually a comma separated list of roles).
Note: this is a re-open of #503 after rebasing.
=> Fix role checking

app/services/order_service.rb, lib/payment_service.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/support/stripe_helper.rb
When a user is presented with SCA and does not go through with it (cancel or fail it), when they resubmit the order, the order goes to `submitted` state which means we send emails to both side and all that jazz without actually processing the charge.
In this case, Order already has a payment intent assigned to it on its `external_charge_id` attribute, so when user resubmits the order, we try to `confirm` that existing payment intent, this leads to a `Stripe::InvalidRequestError` which we were not rescuing from. Since we are doing a optimistic `submit` in our latest code we were not reverting the order.
Rescue from `Stripe::InvalidRequest` in `PaymentService` and create a failed transaction. This way we will revert in `order_service.submit!` and order should be back to `pending` state.
We …
=> Fix fail confirm payment intent issue

.rubocop.yml, app/controllers/errors/error_types.rb, app/jobs/undeduct_line_item_inventory_job.rb, app/services/order_service.rb, lib/payment_service.rb, spec/lib/payment_service_spec.rb
We fixed a scary bug in #510 where we now check for other Stripe errors. But in case payment intent is not even in the state that we attempt confirming (which seems to be the bug we actually ran into) while our previous fix actually works in this case since we added the catch all, at the moment we don't track the fact that we attempted to confirm the payment intent.
Instead of raising `ProcessingError`, actually create a proper `Transaction` in failed state so we can track the fact that user attempted to confirm a payment intent not ready in to be confirmed.
- In `OrderService` as part of #510 we do a `order_processor.revert` in our new catch all block, this potentially means we call revert twice since we get into this block in case of failed payment and requires action, remove the revert …
=> Make sure payment service returns failed transaction on failed confirm

app/events/order_event.rb, spec/events/order_event_spec.rb
We need this value on the APR side to be able to fetch payment intent from Stripe.
cc: @sepans @zephraph going to self-merge since we talked about this and trying to test this on staging since APR side was already merged with this assumption.
=> Add external_charge_id to order event

lib/line_item_helper.rb, lib/offer_totals.rb, lib/order_helper.rb, lib/order_processor.rb, spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/lib/order_processor_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1567
We want to be able to add Radar rules possibly based on artists. We can do this by adding `artist_ids` and `artist_names` to metadata passed to Stripe.
Nous voulons pouvoir ajouter des règles de radar basées éventuellement sur des artistes. Nous pouvons le faire en ajoutant `artist_ids` et` artist_names` aux métadonnées transmises à Stripe.
Add `artist_ids` and `artist_names` for this order to metadata passed to stripe.
Aggiungi `artist_ids` e` artist_names` per questo ordine ai metadati passati a stripe.
=> Add artist ids and names to charge metadata

_schema.graphql, app/admin/orders.rb, app/models/order.rb, app/services/order_cancellation_service.rb, spec/controllers/api/requests/offers/reject_offer_mutation_request_spec.rb, spec/services/order_cancellation_service_spec.rb
When an offer order is canceled/rejected, we still queue jobs to undeduct the inventory. This is not correct because for an offer order at that stage we haven't deducted the inventory yet.
Because of this on the Gravity's end we may end up with artworks with `{"sold":-1,"count":2}` if an offer order on a unique artwork is canceled.
Jira: https://artsyproduct.atlassian.net/browse/PURCHASE-1641
Original slack conversation: https://artsy.slack.com/archives/CB110C6LE/p1572892624036100
Only process undeduct if order is a `BUY` order.
Also added a new cancelation reason for `admin_canceled` to reflect the reality of the case that order was canceled by an admin and not by buyer.
=> Fix admin offer cancelation issue

app/admin/orders.rb
going to self-merge this. This is a followup to #522  where we tried to add both buyer reject and cancel order button but for that to work we have to have 2 separate active admin `action_item`.
#mergeOnGreen
=> [admin] Make sure both buyer_reject and cancel button show up

app/events/transaction_event.rb, spec/events/transaction_event_spec.rb
Looking at APR events, we don't see shipping region for any of our failed transaction events.
`shipping_region` was not in list of order fields exposed in `TransactionEvent`.
Add it.
=> Fix missing shipping_region in TransactionEvent.properties.order

lib/payment_service.rb, spec/controllers/api/requests/submit_order_mutation_request_spec.rb, spec/lib/payment_service_spec.rb, spec/support/stripe_helper.rb
Fixes [PURCHASE-1663](https://artsyproduct.atlassian.net/browse/PURCHASE-1663)
There was an edge-case in the SCA flow that when we tried to confirm the payment intent we'd always error if the intent wasn't in the `requires_confirmation` state. If a user canceled the SCA dialog or came back later to complete their purchase then the confirmation process would happen but with a `requires_action` intent state which would trigger a failure. Essentially it made it where once a user canceled SCA they could never complete their purchase unless they updated their payment information. 
Now during the  confirmation process, if the intent is  in the `requires_action` state  it retriggers the payment intent flow and will reinvoke the SCA process.
=> Ensure user can retry SCA after canceling

app/services/offer_service.rb, lib/payment_service.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/lib/payment_service_spec.rb, spec/support/stripe_helper.rb
When partner's connected account wasn't fully setup, aka. restricted mode. Even when user's card was setup for `off-session` use, the actual `payment_intent` creation failed when partner tried to accept the offer. This failed not because of require action issue and because of that it was not fully reverted. So even if order was not processed, it stayed in `approved` state.
Sample order: https://exchange.artsy.net/admin/orders/99655d85-338d-4e11-ac0f-f97ed83a2d7a
Sample missing charge in our data: https://dashboard.stripe.com/payments/pi_1FImTcGK3Gnpfa3O5TiZRBch
We were not handling generic Stripe errors for accepting offer, we handled those for BN order submission https://github.com/artsy/exchange/pull/512 but we did not do the same for accept offer.
Following the same pattern as …
=> Fix issue with unhandled Stripe error during accept offer

app/services/order_service.rb, lib/order_shipping.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/lib/order_shipping_spec.rb
`setShippng` mutation when `fulfillment_type` is `PICKUP` now processes and saves phone number under order object as `buyer_phone_number`
Fixes [PURCHASE-1656](https://artsyproduct.atlassian.net/browse/PURCHASE-1656)
=> [PURCHASE-1656] Adds phone number to set_shipping mutation pickup mode

.rubocop.yml, app/services/order_cancellation_service.rb, app/services/order_service.rb, lib/order_processor.rb, lib/payment_service.rb, spec/lib/order_processor_spec.rb, spec/lib/payment_service_spec.rb
`PaymentService` used to get list of parameters as input to its methods. It provides method to our payment provider (Stripe) so the caller had to generate all those needed parameters based on the action.
This gets confusing since we have to pass those parameters between few methods and list of them was growing.
Make `PaymentService` a class instead of module and have it initiated using `Order`, this way payment service would be able to generate it's own parameters based on the order. Things like setting metadata and shipping info and etc.
Added `transfer_group` to the passed params and set it to the `Order.id`. cc: @mdole
=> Refactor PaymentService by making it a class and initiate with Order

lib/payment_service.rb, spec/lib/payment_service_spec.rb
Integrity tests started failing after #538 with errors like
https://dashboard.stripe.com/test/logs/req_yfs5btC5dBIW5A
We added `transfer_group` as part of #538 but it was added in wrong place under `transfer_data` while it should have been added in root level based on 
https://stripe.com/docs/api/payment_intents/create#create_payment_intent-transfer_group 
To everyone involved in integrity tests
=> Fix sending transfer_group in wrong spot

lib/gravity.rb, spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/lib/gravity_spec.rb, spec/lib/order_shipping_spec.rb
We found that, because we're only fetching 10 partner locations from gravity, we weren't correctly calculating tax for partners that have > 10 tax nexuses.
=> Fetch all partner locations from gravity

Gemfile, Gemfile.lock
we got reports about collectors not receiving emails when orders are approved.
Sidekiq pods were not working of the queue:
```shell
You are connecting to Redis v3.2.4, Sidekiq requires Redis v4.0.0 or greater
```
Exact same thing as https://github.com/artsy/convection/pull/369
Downgrade Sidekiq
=> Repeat of incident 73 but now on exchange

_schema.graphql, app/controllers/errors/error_types.rb, app/graphql/inputs/shipping_attributes.rb, app/graphql/mutations/set_shipping.rb, app/graphql/types/order_interface.rb, app/graphql/types/requested_fulfillment_union_type.rb, app/services/order_service.rb, lib/order_shipping.rb, spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/integration/gbp/make_offer_happy_path_spec.rb, spec/integration/gbp/reset_shipping_request_spec.rb, spec/integration/reset_shipping_request_spec.rb
__Problem:__
- We want to be able to pre-fill the phone number field on the shipping page if a user has selected pickup, but currently we're not able to fetch for the phone number for pickup orders so this isn't possible.
__Solution:__
- we now return `phone_number` for pickup orders as part of `requested_fulfillment`
- we also updated `setShipping` mutation to now get a root level optional `phone_number`. We kept the `phone_number` passed in shipping as well. so if its not set in the root argument we try to fetch it from shipping input
[PURCHASE-1707]: https://artsyproduct.atlassian.net/browse/PURCHASE-1707
=> Return phoneNumber in graphQL response for CommercePickup order

app/services/order_service.rb, spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb
__Problem:__
We were requiring phone number on pickup orders as well as ship orders, so we were getting validation errors when pickup orders were placed without phone number (phone number field has not been added to reaction yet for pickup orders)
__Solution:__
I changed the validation logic so it only requires phone number for pickup orders. I also added a test to confirm this.
=> Only require phone number for pickup orders

_schema.graphql, app/graphql/types/query_type.rb, db/schema.rb, spec/controllers/api/requests/my_orders_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
We want to be able to show specific user's order in their dashboard.
Add a new `myOrders` query which can be filtered down by:
- `state`
- `sellerId`
and can be sorted same way we currently can sort orders.
It will return a `OrderConnection` for the current user's orders.
A trusted app request will fail.
=> #Hackthon2020 Add myOrders Query

app/admin/orders.rb, app/events/order_event.rb, app/services/order_service.rb, db/migrate/20200116202202_add_fulfilled_by_admin_id_to_orders.rb, db/migrate/20200116202202_add_fulfilled_by_admin_to_fulfillments.rb, db/schema.rb, spec/events/order_event_spec.rb, spec/services/order_service_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-1695
Artsy admins currently can mark orders as fulfilled to clean up the _un-completed_ orders. While that works and tracked in our papertrail logic. We want to capture the fact that this was handled by admins in a more first class way. This way we can make sure emails are not sent in this case and etc.
Add `fulfilled_by_admin_id` to `Order` and when we mark things as fulfilled in admin, we call `confirm_order` and pass newly added `confirmed_by_admin` flag that makes sure `fulfilled_by_admin_id` is set on the `Order`.
Also added `fulfilled_by_admin_id` to `OrderEvent` so consumers can decide what to do based on this being approved by admin or actual user.
=> Add fulfilled_by_admin_id to orders

dangerfile.ts
Hi! 👋 This is my first contribution to an Artsy project! I saw this open issue, so I hope it's still relevant and my PR is helpful. I'm totally happy to make changes to my first stab at it here. One other thing I noticed is that the README is substantially lengthened by the section about `Papertrail Audit Logging` so maybe it could be split off into another markdown file and linked to from the README? Also, I think the numbered list is not exactly working since each item is listed as `1.`. I'd be happy to open issues for either or both of these and take them on, too, if that would be helpful! (I presume they should be numbers `1` through `5`) 😄 
EDIT: Sorry, almost forgot, two tests failed for me locally:
```
rspec ./spec/controllers/api/health_controller_spec.rb:6 # Api::HealthController …
```
=> Add Danger rule about PaperTrail documentation

app/admin/admin_notes.rb, app/admin/fraud_reviews.rb, app/admin/orders.rb, app/models/fraud_review.rb, app/models/order.rb, config/routes.rb, db/migrate/20200124213353_create_fraud_reviews.rb, db/schema.rb
This PR does two things
1. Adds the notion of a fraud review
2. Makes some minor admin notes UI improvements
Currently our fraud review process is highly manual. Our friends over in Consumer Marketplace want to be able to track the manual reviews that happen and report stats on them. 
The `fraud_reviews` model is _very_ similar to the `admin_notes` model. @ashkan18 and I have had a lot of conversations on whether we should consolidate the concepts. At this point, I'm explicitly _not_ combining the two models and accepting that this _may_ be technical debt. The explicit reason is because fraud review and what admin notes are used for are two separate workflows utilized by different people. It's been requested that we do a major overhaul to how admin notes currently is set up and functions. …
=> Add fraud review to exchange

app/admin/orders.rb, lib/payment_service.rb
We've started seeing failures on staging for our cypress integrity tests where we get following error on Stripe:
```
Your destination account needs to have at least one of the following capabilities enabled: transfers, legacy_payments
```
This is a new set of errors that we haven't seen in the past and looks like for these since there is no charge we can't store transactions. This hasn't happened on prod yet but worth adding support for it:
https://sentry.io/organizations/artsynet/issues/1485964863/?project=1275269&query=is%3Aunresolved
As part of #554 we seem to have missed 2 admin calls in admin which lead to 
https://sentry.io/organizations/artsynet/issues/1477952941/?project=1275271&query=is%3Aunresolved
and 
https://sentry.io/organizations/artsynet/issues/1477975587/?project=1275271&q …
=> Fix Stripe capability issue and regression from order cancelation

README.md, dangerfile.ts, docs/papertrail_audit_logging.md
Oops! I need a description! This moves some documentation away from the README, linking to it instead, in the interest of keeping the README doc itself a little shorter.
=> Move PaperTrail documentation to separate file

.circleci/config.yml, Gemfile, Gemfile.lock, Rakefile, hokusai/test.yml, spec/spec_helper.rb
- Replaces `coveralls` with `simplecov` gem, and updates reporting configuration
- Uploads reports after CI test runs via `codecov` orb
Coverage reports for this app available here: https://codecov.io/gh/artsy/exchange
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2072
=> Use Simplecov and Codecov for coverage reporting

hokusai/test.yml
Following up on https://github.com/artsy/exchange/pull/572, which didn't actually work. Think I had it in the wrong place - was able to run `hokusai test` on this branch so 🤞this works better
=> move postgres auth env

lib/gravity.rb, lib/order_processor.rb, spec/lib/gravity_spec.rb, spec/lib/order_processor_spec.rb
Fixing a couple issues that popped up while QAing commission exemption. First, our `dig` statement was always returning `nil` because we were using strings instead of symbols, and second, the object we were trying to return would have had camelCased keys (in `order_processor.rb` we [expect snake_case](https://github.com/artsy/exchange/blob/a22bddbb521c81cf9b3d2d4af42046acb6a1fd53/lib/order_processor.rb#L129)).
=> convert debit return to snake case and add tests

app/services/offer_service.rb, lib/buy_order_totals.rb, lib/offer_order_totals.rb, lib/order_processor.rb, spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb, spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb, spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb, spec/integration/buy_now_commission_exemption_happy_path_spec.rb, spec/integration/buy_now_happy_path_spec.rb, spec/integration/buy_now_sca_path.rb, spec/integration/gbp/buy_now_happy_path_spec.rb, spec/integration/gbp/make_offer_happy_path_spec.rb, spec/integration/gbp/single_counteroffer_happy_path_spec.rb, spec/integration/make_offer_commission_exemption_happy_path_spec.rb, spec/integration/make_offer_happy_path_spec.rb, spec/integration/make_offer_sca_happy_path_spec.rb, spec/integration/single_counteroffer_happy_path_spec.rb, spec/lib/buy_order_totals_spec.rb, spec/lib/offer_order_totals_spec.rb, spec/lib/order_processor_spec.rb, spec/services/offer_service_spec.rb
This PR continues the work started in https://github.com/artsy/exchange/pull/564, adding code that checks for exemptions when an offer is approved. 
With help from @ashkan18, I also moved the logic for calculating exemption to the `[Buy/Offer]OrderTotals` classes. We realized that it made much more sense for the logic determining the final commission after exemption to live with the logic that was responsible for setting commission amounts in general. Plus, this keeps the `order_processor` nice n' streamlined.
This PR also adds simple integration tests for both order and offer - just working on covering our bases here.
[Jira ticket](https://artsyproduct.atlassian.net/browse/GALL-2589)
=> Commission exemption: offers [GALL-2589]

lib/gravity.rb, lib/order_cancelation_processor.rb, lib/order_processor.rb, spec/lib/gravity_spec.rb, spec/lib/order_cancellation_processor_spec.rb, spec/lib/order_processor_spec.rb, spec/services/order_service_spec.rb, spec/system/visiting_order_details_spec.rb
This PR updates Exchange to request a credit to a partner's commission exemption balance in Gravity when an order is refunded in the admin UI.
This work was started in #571. Instead of rebasing that feature branch on master after #564 was merged, I decided to open a new feature branch and manually port over the relevant changes to the refund flow, since there were too many merge conflicts.
=> Credit a Partner's Commission Exemption When an Order Is Refunded (GALL-2588)

app/operations/gravity_graphql/refund_commission_exemption.graphql, lib/gravity.rb, lib/order_cancelation_processor.rb, lib/order_processor.rb, spec/lib/gravity_spec.rb, spec/lib/order_processor_spec.rb, vendor/graphql/schema/gravity.json
Following up on https://github.com/artsy/gravity/pull/12796, this PR switches from consuming the now-nonexistent `credit_commision_exemption` Gravity endpoint to `refund_commission_exemption`. Also grabs the new schema from Gravity using `dotenv bundle exec rake graphql:schema:update`, a handy rake task provided by Artemis
=> Switch from using credit_... to refund_... endpoint

hokusai/production.yml, hokusai/staging.yml
Attempts to address https://artsyproduct.atlassian.net/browse/PLATFORM-2230
Smooth Rollout via calling sleep before shutting down Nginx and Puma to ensure no 504s on deploy.  Also bump maxSurge to 2 to speed up deployment rollouts.
=> tweak rollout settings - add sleep to Nginx and Puma and bump maxSurge to 2 #PLATFORM-2230

lib/address.rb, lib/shipping_helper.rb, spec/lib/shipping_helper_spec.rb
I think this is the easiest way to add this check to this app, and it doesn't allow for bad inputs from the mutation (ie. Sending a shipping address with country 'US' and also a flag `is_eu_shipping destination`)
=> GALL-2637 Add eu country codes and check for that when calculating shipping

.rubocop.yml, .rubocop_todo.yml, Gemfile, Gemfile.lock, app/events/offer_event.rb, app/events/order_event.rb, app/jobs/offer_respond_reminder_job.rb, app/jobs/order_follow_up_job.rb, app/jobs/reminder_follow_up_job.rb, app/models/order.rb, app/models/paper_trail/version.rb, config/environments/development.rb, config/initializers/datadog_statsd.rb, lib/shipping_helper.rb, lib/tasks/graphql.rake, spec/controllers/api/requests/my_orders_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb, spec/events/offer_event_spec.rb, spec/events/order_event_spec.rb, spec/lib/tax/collection_service_spec.rb, spec/models/offer_spec.rb
Exchange had fallen behind on RuboCop so this PR updates it to latest and complies with the new rules. I also switched to the `rubocop-rails` gem which is the current best-practice.
So mostly this is just churn, but I did have to refactor the `ShippingHelper.calculate` method so that I could comply but also so I could better understand what that method did - hopefully people find this easier to change in the future!
=> Upgrade rubocop and switch gem

app/admin/orders.rb, bin/console, bin/pull_data, bin/server, bin/worker
This PR makes some changes to the order page in the admin interface so that we can see if an order came through as the result of a consignment. Here's some before/after screenshots:
<details>
</details>
Note, there was a decent amount of churn in this active admin config file that had nothing to do with my changes. I have broken this out in the individual commits, so might be easier to step through so that the more relevant stuff stands out.
In order to boot up Exchange locally with some data, I wanted to be able to use some of the scripts that I have written over on Convection, so this PR also includes a bunch of those: 
* bin/console
* bin/pull_data
* bin/server
* bin/worker
Probably the more interesting one is that pull data script - this will find the staging db and pull it down …
=> CSGN-121: Add more artwork details to order page

.rubocop.yml, lib/payment_service.rb, spec/lib/payment_service_spec.rb
This PR adds a new key to the metadata sent to Stripe for an order. This new field is called `any_consignment_works` and is set to true if any of the order's line items link to an artwork that has an `import_source` of `convection`.
https://artsyproduct.atlassian.net/browse/CSGN-120
=> CSGN-120: Bubble up consignment flag to stripe

Gemfile, Gemfile.lock, Guardfile, spec/spec_helper.rb
Follows [Convection PR](https://github.com/artsy/convection/pull/505) in adding `Guard`, which will watch tests for changes and re-execute, without having to restart command. Additionally adds the ability to focus on specific tests via the `focus: true` param.
=> [Toolchain] Add Guard for watching tests

Gemfile, Gemfile.lock, app/jobs/record_sales_tax_job.rb, config/initializers/graphql_rails_logger.rb, lib/line_item_totals.rb, lib/offer_totals.rb, lib/order_helper.rb, lib/order_shipping.rb, lib/shipping_helper.rb, lib/tax/calculator_service.rb, spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb, spec/controllers/api/requests/set_shipping_mutation_request_spec.rb, spec/jobs/record_sales_tax_job_spec.rb, spec/lib/line_item_totals_spec.rb, spec/lib/shipping_helper_spec.rb, spec/lib/tax/calculator_service_sepc.rb, spec/lib/tax/collection_service_spec.rb, spec/models/order_spec.rb
Addresses 
- https://artsyproduct.atlassian.net/browse/CSGN-119 
- https://artsyproduct.atlassian.net/browse/CSGN-181
Today our sales tax on BNMO works is calculated by sending taxjar all locations associated with a partner. For direct listings, we will be using one partner account so we only want sales tax to be calculated based on the artwork listing and the buyers address. 
Additionally adds some better logging around our graphql queries via [`graphql-rails_logger`](https://github.com/jetruby/graphql-rails_logger).  
<details><summary>Screenshots</summary>
With Tax: 
Without Tax: 
With Tax: 
Without Tax: 
</details>
=> [Consignments] If consignment only use artwork location and buyer location for calculating tax

hokusai/production.yml, hokusai/staging.yml
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2594
See https://www.notion.so/artsy/Nginx-Ingress-Controllers-4b5d937f0acd480f938c34ef1509d3c4 and the section Migrating an application from an external LoadBalancer-fronted service to an Ingress-fronted service.
1. Merge this PR and wait for changes to be deployed to Staging.
2. Test the newly created Ingress in Staging by:
`curl -i -H "host: exchange-staging.artsy.net" -k https://a2b7b9ff4afbf11ea976f123b14b93be-bc5647bbe8f5b617.elb.us-east-1.amazonaws.com`
3. Switch Staging DNS to Ingress by updating on Cloudflare as follows:
`exchange-staging.artsy.net` -> `a2b7b9ff4afbf11ea976f123b14b93be-bc5647bbe8f5b617.elb.us-east-1.amazonaws.com`
4. Merge the Deploy PR that will be automatically generated. Wait for changes to be …
=> #migration Add Ingress resource in hokusai/staging.yml and hokusai/production.yml. Switch DNS to Ingress

hokusai/production.yml, hokusai/staging.yml
Follow-up to #626
- Remove ELB service
- Remove Nginx sidecar
1. Merge and deploy
2. Delete the old ELB service with `kubectl delete service exchange-web`
=> #migration Clean up ELB services and Nginx sidecar

app/admin/orders.rb, app/graphql/mutations/confirm_fulfillment.rb, app/graphql/mutations/confirm_pickup.rb, app/models/admin_note.rb, app/models/order.rb, app/services/order_service.rb, spec/controllers/api/requests/confirm_fulfillment_request_spec.rb, spec/controllers/api/requests/confirm_pickup_request_spec.rb, spec/services/order_service_spec.rb
Fixes [PURCHASE-1715](https://artsyproduct.atlassian.net/browse/PURCHASE-1715)
Problem:
MSO team is not able to report offline sales in exchange. This involves changing the state from `canceled` or `abandoned` (why? [discussion here](https://artsyproduct.atlassian.net/browse/PURCHASE-1715?focusedCommentId=31124)) to `fulfilled` as well as editing prices and the fulfillment date. There is no need to capture credit card or send emails since the sale has happened off-platform.
Solution:
Admins now have the ability to confirm offline sale on canceled and abandoned orders and edit prices/date. This also automatically adds an 'Admin note'.
<details><summary>Screenshots</summary>
The button (only appears on abandoned/canceled orders):
This form shows up after pressing the button:
Changes to …
=> [PURCHASE-1715] Add 'Confirm offline sale' button

app/admin/orders.rb
<details><summary>Screenshots</summary>
Before:
After:
</details>
Updating `actions` to `actions :all, except: %i[create destroy new]` in https://github.com/artsy/exchange/pull/636 added the `edit_admin_order_path` path (used for confirm sale button) as well as adding the actual button to page. 
That new `edit` button is not needed and also dangerous. This piece of code removes that. [source](https://stackoverflow.com/questions/44723359/how-do-you-remove-the-edit-button-in-an-active-admin-show)
=> Remove order edit button from active admin order page

.rubocop.yml, app/admin/admin_notes.rb, app/admin/fraud_reviews.rb, app/admin/orders.rb
Noticed in https://github.com/artsy/exchange/pull/637#discussion_r487205381 Rubocop wasn't running for Active Admin files. Instead of disabling Rubocop entirely for Active Admin files, let's only disable `Metrics/BlockLength` rule for them (given the Active Admin files tend to be long).
I ran `bundle exec rubocop -a` and manually fixed a few (commented inline).
=> Enable Rubocop for active admin files

app/admin/orders.rb, app/controllers/errors/error_types.rb, app/models/order.rb, spec/models/order_spec.rb
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2113
Follow up to https://github.com/artsy/exchange/pull/636
When creating the offline sale information form forgot to include the artwork price and offer price. This PR adds that. Offer price is straight forward since it is an attribute on `Order` model but artwork price was a bit more tricky because it is derived from sum of `LineItem` prices times their quantity. We currently only have a single `LineItem` on orders and the quantity is always 1 so the new function only handles that case and throws an error if that's not the case. We have a few old orders on production that were manually modified and have multiple line items but no need to worry about that since this 'Offline Sale' is not applicable to them.
=> [PURCHASE-2113] Make price/offer editable

_schema.graphql, app/graphql/types/query_type.rb, spec/controllers/api/requests/my_orders_query_request_spec.rb
On the purchase history page, we don't want to show the `abandoned` orders but if we do the filtering on the client-side the pagination wouldn't work as expected so we need to do the filtering on the server-side,
This will change the `state` params to `states` to be able to pass an array of states (everything except 'abandoned') from the client.
This is a schema breaking change but since we haven't launched purchase history yet it is safe to synchronously deploy it
=> Change `myOrders` query to accept multiple states

Dockerfile, Gemfile, Gemfile.lock, spec/lib/time_zone_spec.rb
Fixes a silent failure regarding time zone parsing, resulting from updates to the IANA time zone database.
This follows the pattern in:
- https://github.com/artsy/vortex/pull/279
- https://github.com/artsy/diffusion/pull/347
- https://github.com/artsy/volt/pull/4697
Discussion here:
https://artsy.slack.com/archives/C9ZJYFDNF/p1603137517274800
and here:
https://artsy.slack.com/archives/C02BC3HEJ/p1603289217394000
=>  fix: prefer tzinfo-data gem over tzdata package

lib/order_processor.rb, spec/lib/order_processor_spec.rb
Fixes [PURCHASE-2242](https://artsyproduct.atlassian.net/browse/PURCHASE-2242)
Problem:
When a submitted order gets reverted we don't leave enough paper trail to troubleshoot the problem
Solution:
Log revert reason to Rails logger for better troubleshooting
=> chore: Log revert reason

spec/integration/inquiry_checkout_happy_path_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-2338
To identify major changes needed in Exchange to support Inquiry Checkout, we can follow existing patterns to add a new integration spec that maps 1:1 how UI calls Exchange GraphQL mutation and interact with the system. In the spec I used all the existing mutations to step through the major Inquiry Checkout flow and mocked features that will need to be built.
The goal of this PR is to help creating major tasks for this project. While we implement the features, we can remove the mocks in the specs and turn it into a real integration test.
=> Add a mocked integration spec for basic inquiry checkout flow

config/puma.config
`daemonize` has been removed in Puma 5. Removing it should behave the same since we want to run it on the foreground.
> tcp mode and daemonization have been removed without replacement. For
daemonization, please use a modern process management solution, such as
systemd or monit.
https://github.com/puma/puma/blob/master/5.0-Upgrade.md#upgrade
The error can be reproduced when running `BUNDLE_GITHUB__COM=... hokusai dev start`:
=> fix: remove unsupported daemonization in Puma 5

hokusai/development.yml, hokusai/test.yml
When running `hokusai dev start`, postgres gives an error of
```
Database is uninitialized and superuser password is not specified.`
```
This follows the prompt and existing pattern in [Gravity](https://github.com/artsy/gravity/blob/6d5ea778793cf9ce095494a3cc55a0485b207efd/hokusai/development.yml#L113) to set
```
POSTGRES_HOST_AUTH_METHOD=trust
```
and allow connection without password in hokusai dev.
=> fix: allow postgres connection without password in hokusai dev

lib/order_creator.rb, spec/lib/order_creator_spec.rb, spec/support/gravity_helper.rb
This PR enables artworks with Gravity's `offerable_from_inquiry` property to be valid for orders.
cc @artsy/purchase-devs 
https://artsyproduct.atlassian.net/browse/PURCHASE-2412
=> Allow offerable from inquiry artworks to pass order validation

_schema.graphql, app/graphql/types/offer_order_type.rb, lib/order_creator.rb, spec/controllers/api/requests/offers/create_inquiry_offer_order_with_artwork_mutation_request_spec.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/services/order_service_spec.rb
Addresses [PURCHASE-2418](https://artsyproduct.atlassian.net/browse/PURCHASE-2418)
This PR expands the `OfferOrderType` to include `impulse_conversation_id`. The `impulse_conversation_id` wasn't getting persisted to the database so this also updates creation transaction inside the OrderCreator file.
[Corresponding metaphysics PR](https://github.com/artsy/metaphysics/pull/2977)
cc: @artsy/purchase-devs
=> Fix: persist impulse_conversation_id

_schema.graphql, app/graphql/types/query_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb
This PR adds a field `impulseConversationId` to the `orders` query field to allow filtering by conversation ID. `buyerId` or `sellerId` is still required.
🔒 [slack conversation that led to this change](https://artsy.slack.com/archives/C9YNS4X32/p1614119355107900)
=> feat: filter orders query field by conversation

_schema.graphql, app/graphql/types/events/order_state_changed_event.rb, app/services/order_history_service.rb, spec/controllers/api/requests/order_history_request_spec.rb, spec/services/order_history_service_spec.rb
This pr builds on https://github.com/artsy/exchange/pull/683 with a minor naming change: `OrderStateChangedEvent#type` -> `#state`. Up for debate whether we want to do it but the change would be easier now than later.
=> Update new graphql schema to be less ambiguous

app/controllers/errors/application_error.rb, app/models/order.rb, app/services/inventory_service.rb, app/services/offer_service.rb, app/services/order_service.rb, lib/offer_processor.rb, lib/order_processor.rb, spec/controllers/errors/application_error_spec.rb, spec/integration/inquiry_checkout_happy_path_spec.rb, spec/lib/offer_processor_spec.rb, spec/lib/order_processor_spec.rb, spec/models/order_spec.rb, spec/services/inventory_service_spec.rb, spec/services/offer_service_spec.rb, spec/services/order_service_spec.rb, spec/support/gravity_helper.rb, spec/support/offer_query_helper.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-2471
(I did some refactoring and it might be easier to review by commits.)
Given that inquiry artworks don't have accurate inventory information (and we don't want partners to provide them upfront in Inquiry Checkout), we are going to relax the requirements on inventory for inquiry orders. That is,
- Do not check inventory
- Do not deduct/un-deduct inventory during the order lifecycle
I did an audit of how we currently handle inventory:
**Buy Now**
- Deduct inventory when a BN order is [submitted](https://github.com/artsy/exchange/blob/b271a36d5bd44d506ecd4bde5d1799fce79a1e99/app/services/order_service.rb#L54)
- Un-deduct inventory when [BN order submission failed](https://github.com/artsy/exchange/blob/b271a36d5bd44d506ecd4bde5d1799fce79a …
=> feat: do not require inventory for inquiry orders (PURCHASE-2471)

app/services/stripe_webhook_service.rb, lib/line_item_helper.rb, spec/services/inventory_service_spec.rb, spec/services/stripe_webhook_service_spec.rb
https://artsyproduct.atlassian.net/browse/PURCHASE-2471
Following https://github.com/artsy/exchange/pull/687, I missed one place where we un-deduct inventory when receiving a refund webhook from Stripe. This skips it for inquiry orders.
I also fixed the line item helper for determining if a line item has inventory when it's `nil` (currently it raises an error).
=> feat: do not un-deduct inventory for inquiry orders when receiving Stripe refund webhook (PURCHASE-2471)

app/graphql/types/query_type.rb, spec/controllers/api/requests/order_query_request_spec.rb, spec/controllers/api/requests/orders_query_request_spec.rb
Following up on https://github.com/artsy/volt/pull/4982. I originally missed that we were gatekeeping access to orders both in the Volt UI and in Exchange. This PR allows users with the `sales_observer` role to execute `order` and `orders` queries, but does _not_ allow them access to Exchange admin UI or to any mutations.
There are tests in place for the query permissions, and I confirmed the "no access to Exchange UI" via the following steps:
1. Started local Exchange server at localhost:3000
2. Opened Gravity staging console
3. `user = User.find_by_email 'matt.dole@artsymail.com'`
4. `user.update!(roles: ["admin", "customer_support", "billing_admin", "team", "sales_observer"])`
5. Opened incognito window, logged in and confirmed I was unable to access
6. `user.update!(roles: ["admin", …
=> feat: allow sales_observers to execute order queries

_schema.graphql, app/controllers/errors/error_types.rb, app/graphql/types/query_type.rb, spec/controllers/api/requests/orders_query_request_spec.rb
Addresses: [PURCHASE-2500](https://artsyproduct.atlassian.net/browse/PURCHASE-2500)
This is a work in progress for expanding the orders query to support filtering by multiple states.
**Filter by states argument:**
**Error when both `state` and `states` arguments are passed:**
=> WIP: expand orders to accept a new states argument

lib/transaction_fee_calculator.rb, spec/lib/transaction_fee_calculator.spec.rb
Update Exchange to not calculate Stripe fees on staging.
This PR introduces a new environment variable:  `NEW_TRANSACTION_FEE_ENABLED` that enables us to test not returning Stripe transaction fees in Staging only.
cc @artsy/purchase-devs 
https://artsyproduct.atlassian.net/browse/PURCHASE-2567
=> feat: return 0 for stripe fees on staging
